Add logging storage to admin server
linuxboot/contest pull request #101
Opened 2022-07-14 13:06 UTC by mahmednabil109

- add http logger hook and make it async
- add mongodb storage

Signed-off-by: Mohamed Abokammer <mahmednabil109@gmail.com>

2022-07-15 12:50 UTC, mimir-d requested changes
some changes required; some optional

2022-07-15 12:50 UTC, mimir-d commented on pkg/loggerhook/httphook.go
> +func (hh *HttpHook) fire(ctx xcontext.Context) {
```suggestion
func (hh *HttpHook) logHandler(ctx xcontext.Context) {
```

2022-07-15 12:50 UTC, mimir-d commented on pkg/loggerhook/httphook.go
> +	hh.logChan <- storage.Log{
could add a timeout here, for safety (prob 1 second is enough)

2022-07-15 12:50 UTC, mimir-d commented on pkg/loggerhook/httphook.go
> +	if addr[len(addr)-1] != '/' {
might wanna use this https://pkg.go.dev/net/url or some url builder

2022-07-15 12:50 UTC, mimir-d commented on pkg/loggerhook/httphook.go
> +			fmt.Printf("Closing http logger")
nit; this should prob be on stderr

2022-07-15 12:50 UTC, mimir-d commented on pkg/loggerhook/httphook.go
> +func NewHttpHook(ctx xcontext.Context, addr string) *HttpHook {
youre not checking if input is valid, this would return (*HttpHook, error) in that case

2022-07-15 12:50 UTC, mimir-d commented on docker-compose.yml
> +            dockerfile: docker/contest/Dockerfile
add a comment here to say why it's ok to use the contest dockerfile

2022-07-15 12:50 UTC, mimir-d commented on docker-compose.yml
> +            - 8000:8000
it's likely that you dont need to expose this port since all the traffic is in the "net" bridge. should check

2022-07-15 12:50 UTC, mimir-d commented on cmds/admin_server/storage/storage.go
> +// SearchOpt defines the different options to filter with
```suggestion
// SearchQuery defines the different options to filter with
```

or just Query, and remove the Query string; was that supposed to be text search? if so, rename to Text?

2022-07-15 12:50 UTC, mimir-d commented on cmds/admin_server/storage/storage.go
> +	EndDate   string `json:"endDate"`
why are these marked for json?

2022-07-15 12:50 UTC, mimir-d commented on cmds/admin_server/server/server.go
> +	if err != nil {
you should add an error type here for "not supported". the storage.Storage should always be able to provide logs, but is not always writable

2022-07-15 12:50 UTC, mimir-d commented on cmds/admin_server/main.go
> +	storage, err := mongoAdapter.NewMongoStorage(*flagDBURI)
defer close

2022-07-15 12:50 UTC, mimir-d commented on tests/integ/admin_server/logendpoint_test.go
> +func setupClearDB(uri string) (*mongo.Client, error) {
nit
```suggestion
func setupCleanDB(uri string) (*mongo.Client, error) {
```

or empty (clear is more like "transparent")

2022-07-15 12:50 UTC, mimir-d commented on tests/integ/admin_server/logendpoint_test.go
> +	defer cancel()
the moment you exit this func, the cancel is called; does this affect the Connect?

2022-07-15 12:50 UTC, mimir-d commented on tests/integ/admin_server/logendpoint_test.go
> +	db, err := setupClearDB(*flagMongoEndpoint)
nit; move this closer to the usage site (around line 86)

2022-07-15 12:50 UTC, mimir-d commented on tests/integ/admin_server/logendpoint_test.go
> +	cur, err := db.Database(mongoAdapter.DefaultDB).
you extracted submitLog, you can also extract this "get all logs"

2022-07-15 12:54 UTC, mimir-d commented on pkg/loggerhook/httphook.go
> +	go hh.fire(ctx)
this seems to be what you want, in order to not leak the goro
https://pkg.go.dev/github.com/sirupsen/logrus#DeferExitHandler

2022-07-15 14:05 UTC, mahmednabil109 commented on cmds/admin_server/storage/storage.go
> +	EndDate   string `json:"endDate"`
I intended to use it with gin query bind, but it should be marked with form not json. i modified it locally

2022-07-15 14:06 UTC, mahmednabil109 commented on cmds/admin_server/main.go
> +	storage, err := mongoAdapter.NewMongoStorage(*flagDBURI)
done locally :)

2022-07-15 14:18 UTC, mahmednabil109 commented on pkg/loggerhook/httphook.go
> +	go hh.fire(ctx)
as I understand it will be not simple to use it. i think it should be like this 
```go
exitChan := make(chan struct{})
DeferExitHandler(func(){ exitChan <- struct{}{} })
```
and then wait on the exit channel. but the context cancellation is more convenient i think.

2022-07-15 14:23 UTC, mahmednabil109 commented on tests/integ/admin_server/logendpoint_test.go
> +	defer cancel()
It didn't, i guess because the driver is no more listening on the context channel as the connection is created successfully. but i agree it shouldn't be there.

2022-07-15 15:23 UTC, mahmednabil109 commented on cmds/admin_server/server/server.go
> +	if err != nil {
Sorry, I didn't get this.

2022-07-15 20:10 UTC, mimir-d commented on cmds/admin_server/server/server.go
> +			c.JSON(http.StatusInternalServerError, gin.H{"status": "err", "msg": "unkown error!"})
```suggestion
			c.JSON(http.StatusInternalServerError, gin.H{"status": "err", "msg": "unknown server error"})
```

2022-07-15 20:11 UTC, mimir-d commented on cmds/admin_server/server/server.go
> +		case errors.Is(err, storage.ErrDBInsert):
```suggestion
		case errors.Is(err, storage.ErrInsert):
```

2022-07-15 20:14 UTC, mimir-d commented on cmds/admin_server/server/server.go
> +	// insret the log into the storage system
```suggestion
	// insert the log into the storage system
```

2022-07-15 20:18 UTC, mimir-d commented on pkg/loggerhook/httphook.go
> +		fmt.Fprintf(os.Stderr, "Logging Fire timeout")
you should also print what we missed here

2022-07-15 20:27 UTC, mimir-d commented on docker-compose.yml
> +            - 27017:27017
this doesnt need exposing either; it's only used by the admin-server container; for visibility though, add the port arg (whatever that is for mongod), to match with the dbURI

2022-07-15 20:28 UTC, mimir-d commented on cmds/admin_server/storage/mongo/mongo.go
> +func (s *MongoStorage) GetLogs(opt storage.Query) ([]storage.Log, error) {
```suggestion
func (s *MongoStorage) GetLogs(query storage.Query) ([]storage.Log, error) {
```

2022-07-15 20:29 UTC, mimir-d commented on cmds/admin_server/storage/storage.go
> +	EndDate   string `json:"endDate"`
ok, but this isnt used in the PR; you should add these whenever you also use queryBind

2022-07-15 20:32 UTC, mimir-d commented on cmds/admin_server/server/server.go
> +	var logBody storage.Log
the type is Log, the method is called StoreLog, so why logBody
```suggestion
	var log storage.Log
```

2022-07-15 20:34 UTC, mimir-d commented on cmds/admin_server/storage/mongo/mongo.go
> +	DefaultDB                = "admin-server-db"
is this schema created on first usage?

2022-07-15 20:35 UTC, mimir-d commented on cmds/admin_server/storage/mongo/mongo.go
> +	DefaultConnectionTimeout = 10 * time.Second
are these exported outside this package?

2022-07-15 20:36 UTC, mimir-d commented on cmds/admin_server/storage/mongo/mongo.go
> +	// for better debugging
nit; move this before the printf; the `if err != nil` is not for better debugging

2022-07-15 20:39 UTC, mimir-d commented on cmds/admin_server/storage/mongo/mongo.go
> +	storage.Log `json:"log"`
is there a requirement for this json tag?

2022-07-15 20:41 UTC, mimir-d commented on cmds/admin_server/storage/storage.go
> +	JobID    uint64    `json:"jobID"`
you should be very careful when mixing storage schema with restapi presentation schema. youre using this object for both now, it may be the case that those 2 diverge in the future

same goes for the query struct; note how it has `form` tags but it's inside the storage package, that has no idea what that form is

you dont need to address this now, but keep in mind

2022-07-15 20:49 UTC, mimir-d commented on pkg/loggerhook/httphook.go
> +	go hh.logHandler(ctx)
now cancelling the goro like this works. but passing ctx to a constructor func doesnt quite make sense. the semantic would be that the construction may somehow be cancelled (may also be viewed as storing the ctx in the struct itself, because it is essentially stored by the closure here; this is also not recommended)

what you should do here is:
option 1: add a done chan in HttpHook, and a `Close` method that stops the goro (careful to make Close no-op for an already closed hook)
option 2: still use a ctx for logHandler (it makes sense ther), but make the context with cancellation here, and return the cancel func (ret would be (*HttpHook, func(), error))

for me option 1 makes more sense, the hook itself now own resources (the goro), which are dealloc by Close

2022-07-15 20:55 UTC, mimir-d commented on tests/common/goroutine_leak_check/goroutine_leak_check.go
> +	time.Sleep(80 * time.Millisecond)
you can make this even bigger (<0.5s)

2022-07-18 09:38 UTC, mahmednabil109 commented on docker-compose.yml
> +            - 27017:27017
yes, it's not needed but it's helpful for manual debugging.

2022-07-18 09:41 UTC, mahmednabil109 commented on cmds/admin_server/storage/mongo/mongo.go
> +	DefaultDB                = "admin-server-db"
yes, this is how mongo works, but i can add a script to a dockerfile to manually create the database and the collection. I am planning to do that while defining the indexes.

2022-07-18 09:42 UTC, mahmednabil109 commented on cmds/admin_server/storage/mongo/mongo.go
> +	DefaultConnectionTimeout = 10 * time.Second
yes, it is used in the integ testing

2022-07-18 12:35 UTC, mimir-d commented on cmds/admin_server/storage/mongo/mongo.go
> +	DefaultDB                = "admin-server-db"
yeah, that would be better for visibility

2022-07-18 14:13 UTC, mimir-d approved these changes

2022-07-18 14:13 UTC, mimir-d commented on pkg/xcontext/bundles/logrusctx/new_context.go
> +			// clean the http logger when on cxt canceling
```suggestion
			// clean the http logger when on ctx canceling
```

2022-07-18 14:13 UTC, mimir-d commented on cmds/admin_server/storage/mongo/mongo.go
> +	DefaultDB                = "admin-server-db"
add a comment here to reference the initdb.js file; there's another `admin-server-db` there and it needs to match this one

2022-07-18 14:41 UTC, mimir-d approved these changes

2022-07-18 14:41 UTC, merged

2022-07-20 15:03 UTC, rihter007 commented on cmds/admin_server/storage/mongo/mongo.go
> +func NewMongoStorage(uri string) (storage.Storage, error) {
nit

Sorry for delay, I would pass a context to this function for client to control the timeout as well

2022-07-20 15:03 UTC, rihter007 commented on cmds/admin_server/storage/mongo/mongo.go
> +func NewMongoStorage(uri string) (storage.Storage, error) {
nit

Sorry for delay, I would pass a context to this function for client to control the timeout as well

2022-07-20 15:04 UTC, rihter007 commented on cmds/admin_server/storage/mongo/mongo.go
> +	err = client.Ping(context.Background(), nil)
nit

why don't we use the same context here?

2022-07-20 15:05 UTC, rihter007 commented on cmds/admin_server/storage/mongo/mongo.go
> +func (s *MongoStorage) StoreLog(log storage.Log) error {
nit

I would add ctx context.Context as the first parameter

2022-07-20 15:06 UTC, rihter007 commented on cmds/admin_server/storage/mongo/mongo.go
> +func (s *MongoStorage) StoreLog(log storage.Log) error {
@mimir-d

Usually logging is done as batch to reduce costs, should we try to do it as well? (at least plan)

2022-07-20 15:07 UTC, rihter007 commented on cmds/admin_server/storage/storage.go
> +	JobID    uint64    `json:"jobID"`
nit

I would also propose to use snake-case "job_id"

2022-07-20 15:34 UTC, xaionaro commented on cmds/admin_server/storage/mongo/mongo.go
> +func (s *MongoStorage) StoreLog(log storage.Log) error {
My 2 cents:
I agree with batches in long term, but it seems to be very low-pri thing at this stage.

2022-08-24 16:24 UTC, xaionaro commented on pkg/loggerhook/httphook.go
> +	hh.closeChan <- struct{}{}
Better to do `close(hh.closeChan)`. This way all consumers of the channel will be unblocked (not only one).