Add log query endpoint
linuxboot/contest pull request #103
Opened 2022-07-19 11:44 UTC by mahmednabil109

- add GET `log` endpoint to query logs
- support text search, date and log level filtering
- add integ test for the log query endpoint

Signed-off-by: Mohamed Abokammer <mahmednabil109@gmail.com>

2022-07-19 16:18 UTC, mimir-d commented on tests/integ/admin_server/getlogs_test.go
> +		ll := logLevels[rand.Intn(len(logLevels))]
```suggestion
		level := logLevels[rand.Intn(len(logLevels))]
```

2022-07-19 16:23 UTC, mimir-d commented on tests/integ/admin_server/getlogs_test.go
> +	defer db.Disconnect(context.Background())
you should always have timeouts in tests so that they dont hang forever

2022-07-19 16:25 UTC, mimir-d commented on tests/integ/admin_server/getlogs_test.go
> +		apiQurey storage.Query
```suggestion
		apiQuery storage.Query
```

2022-07-19 16:29 UTC, mimir-d commented on tests/integ/admin_server/getlogs_test.go
> +	endDate := time.Now().Add(1 * time.Second)
should add a comment here to explain why this date range is guaranteed to match some data

2022-07-19 16:35 UTC, mahmednabil109 commented on cmds/admin_server/server/server.go
> +		c.JSON(http.StatusBadRequest, gin.H{"status": "err", "msg": "bad formatted query"})
i'll take a look

2022-07-19 16:39 UTC, mahmednabil109 commented on cmds/admin_server/storage/mongo/mongo.go
> +		logs = append(logs, log.Log)
it keeps "_id", and I use _embedding_ that to easily add any database specific fields

2022-07-19 16:44 UTC, mahmednabil109 commented on tests/integ/admin_server/getlogs_test.go
> +			require.Equal(t, len(dbLogs), int(result.Count))
I was counting on their randomness as it's not likely to have all these queries collided with others in the same time. but yes, i should add text field check to be 100% sure.

2022-07-20 11:47 UTC, mimir-d commented on cmds/admin_server/storage/mongo/mongo.go
> +		if len(q) == 2 {
this check is very brittle; someone might just add another item above with another filter in the future and this completely breaks

2022-07-20 11:47 UTC, mimir-d commented on cmds/admin_server/storage/mongo/mongo.go
> +				"$regex": primitive.Regex{Pattern: *query.Text, Options: "ig"},
youre assuming this exists, and i said in a prev comment that all query fields should be optional (the one with making them pointers)

2022-07-20 11:47 UTC, mimir-d commented on cmds/admin_server/storage/storage.go
> +	Text      *string    `form:"text" binding:"required"`
all of these are optional; incl the text and paging

2022-07-20 11:47 UTC, mimir-d commented on tests/integ/admin_server/getlogs_test.go
> +		{
you posted new code but im not seeing these 2 cases requested above

2022-07-20 11:47 UTC, mimir-d commented on cmds/admin_server/storage/mongo/mongo.go
> +		logs = append(logs, log.Log)
got it; "log.Log" reads weird though

2022-07-20 12:05 UTC, mahmednabil109 commented on tests/integ/admin_server/getlogs_test.go
> +	t.Run("no-filters", func(t *testing.T) {
@mimir-d, here is the requested cases

2022-07-20 12:08 UTC, mahmednabil109 commented on cmds/admin_server/storage/mongo/mongo.go
> +				"$regex": primitive.Regex{Pattern: *query.Text, Options: "ig"},
yes, i assumed that as I marked it as required. but, that's right this function has no idea about the api validation. I should cover this case.

2022-07-20 12:12 UTC, mimir-d requested changes

2022-07-20 12:12 UTC, mimir-d commented on tests/integ/admin_server/getlogs_test.go
> +			ctx, cancel := context.WithTimeout(context.TODO(), time.Duration(*flagTimeout)*time.Second)
this is incorrect; you labelled flagTimeout as "test timeout" and you use it as "operation timeout". Test timeout implies that the whole test will take a maximum of that time, so if that's what you want, you need to make this timeout context be test-wide (over all cases and setup).
Alternative is to re-define the timeout to be "operation timeout", and you can use it like you already are.

2022-07-20 12:12 UTC, mimir-d commented on tests/integ/admin_server/getlogs_test.go
> +	tabel := make(map[string]bool)
should also explain (in comment) that youre using this as an index of log data that has been seen, and this works because the text is randomly generated, so this can act as a key in "table"

2022-07-20 12:12 UTC, mimir-d commented on cmds/admin_server/storage/storage.go
> +	if q.Page == nil || *q.Page == 0 {
note; paging should start from 0, that's the general expectation in apis

2022-07-20 12:33 UTC, mahmednabil109 commented on tests/integ/admin_server/logendpoint_test.go
> +	flagTimeout       = flag.Int("timeout", 10, "test timeout in seconds")
it get parsed automatically in the test files.

2022-07-20 16:18 UTC, mahmednabil109 commented on tests/integ/admin_server/getlogs_test.go
> +			ctx, cancel := context.WithTimeout(context.TODO(), time.Duration(*flagTimeout)*time.Second)
yeah, i am using it as an operation timeout, go already supports a flag for test timeout. I will rename it.

2022-07-20 18:35 UTC, rihter007 commented on cmds/admin_server/storage/mongo/mongo.go
> +		fmt.Fprintf(os.Stderr, "Error while performing count query: %v", err)
nit

Wondering why don't we use fancy @xaionaro's logging?

2022-07-20 18:35 UTC, rihter007 commented on cmds/admin_server/storage/mongo/mongo.go
> +		return nil, storage.ErrQuery
Would be nice to add original err

2022-07-20 18:37 UTC, rihter007 commented on cmds/admin_server/storage/mongo/mongo.go
> +	if *query.PageSize < uint(pageSize) {
Despite resolving defaults, I would add a PageSize != nil check

2022-07-20 18:40 UTC, rihter007 commented on cmds/admin_server/storage/mongo/mongo.go
> +	ctx, cancel = context.WithTimeout(context.Background(), DefaultConnectionTimeout)
we loose the initial cancel that should be called anyway

2022-07-20 18:44 UTC, rihter007 commented on cmds/admin_server/storage/mongo/mongo.go
> +	var logs []storage.Log
nit

One can save allocation (which of course will not change anything) by

logs = make([]storage.Log, 0, len(mlogs))

2022-07-20 18:45 UTC, rihter007 commented on cmds/admin_server/storage/storage.go
>  	StoreLog(Log) error
Let's add ctx to the interface in case client would like to terminate the operation earlier than our default connection timeout?

2022-07-20 18:47 UTC, rihter007 commented on tests/integ/admin_server/getlogs_test.go
> +		continueRetrieve = continueRetrieve && retrieveAll && (int64(result.Count)-int64((currentPage)*(*query.PageSize)) > 0)
nit

continueRetrieve is always true?

2022-07-20 18:47 UTC, rihter007 commented on tests/integ/admin_server/getlogs_test.go
> +	ctx, cancel := context.WithTimeout(context.TODO(), time.Duration(*flagOperationTimeout)*time.Second)
nit

TODO -> Background

2022-07-20 18:49 UTC, rihter007 requested changes
All in all looks good, but there are small things that can make code a bit better

2022-07-20 19:55 UTC, mahmednabil109 commented on cmds/admin_server/storage/mongo/mongo.go
> +		return nil, storage.ErrQuery
I think it's not the concern of the frontend to know the details of the err. And I am logging it already in the server for debugging.

2022-07-20 20:07 UTC, mahmednabil109 commented on cmds/admin_server/storage/mongo/mongo.go
> +		fmt.Fprintf(os.Stderr, "Error while performing count query: %v", err)
yeah, while passing ctx to support function cancellation, I could get the logger from the ctx.

2022-07-20 22:00 UTC, mahmednabil109 commented on cmds/admin_server/storage/mongo/mongo.go
> +	ctx, cancel = context.WithTimeout(context.Background(), DefaultConnectionTimeout)
> we loose the initial cancel 

- it's already defered, and if there is a case when we will need to call `cancel()` so it would be between the two declartion. so what is the problem exactly.

- okay where should this function be, should I make a utils pkg.

2022-07-20 23:51 UTC, mimir-d commented on cmds/admin_server/server/server.go
> +	if query.Page == nil {
not worth having a function for 2 ifs; the originating function is already short enough

if you really want to extract this, take the whole block dealing with the query, like
```
query, err := getQueryFromContext(c)
```

but i wouldnt really bother with extracting that. it's already clear in the initial function and the new func just polutes global namespace

2022-07-20 23:51 UTC, mimir-d commented on tests/integ/admin_server/getlogs_test.go
> +	t.Run("no-paging", func(t *testing.T) {
why didnt these 2 cases fit in the same array above?

2022-07-20 23:51 UTC, mimir-d commented on cmds/admin_server/storage/storage.go
>  	StoreLog(Log) error
that's a very good point; all of these methods should take ctx for cancellation. but since this comment also covers existing code, post another PR fixing this

2022-07-20 23:51 UTC, mimir-d commented on tests/integ/admin_server/logendpoint_test.go
> +	flagTimeout       = flag.Int("timeout", 10, "test timeout in seconds")
cool, but youre defining them in one _test.go file and using in others as well. it would be more clear to have a flags_test.go file with just these vars in it

2022-07-20 23:52 UTC, mimir-d commented on tests/integ/admin_server/logendpoint_test.go
> +	ctx, cancel := context.WithTimeout(context.Background(), time.Duration(*flagTimeout)*time.Second)
this is becoming a requirement. there's nothing stopping a user to say -20 for that flag, where the parseduration at least enforces some validation

2022-07-21 00:16 UTC, mimir-d requested changes

2022-07-21 00:16 UTC, mimir-d commented on cmds/admin_server/storage/mongo/mongo.go
> +		fmt.Fprintf(os.Stderr, "Error while performing count query: %v", err)
do not store ctx in structs; it is specifically not recommended by docs.
in the next pr, where you add ctx to all Storage interface methods, you can have it be xcontext and get the logging that way, along with the  cancellation that you need for all these operations (replacing context.Background)

2022-07-21 00:16 UTC, mimir-d commented on cmds/admin_server/storage/mongo/mongo.go
> +	if *query.PageSize < uint(pageSize) {
and this is where you start to see the subtleties i was refering to when i said not to mix rest api objects with database objects. youre using the rest api model here in the api for database, and because of that, you need to drag this nil check here.
if you had different objects, the rest api could have the pointers (to check if the client actually gave you that in the query) and the db query would have a non-ptr here (resolved from the rest api object, after defaults, validations, etc).
issues for this are only gonna multiply as code evolves, but again, im writing this just for didactic purposes. you can keep these objects as is for the PR

2022-07-21 00:16 UTC, mimir-d commented on cmds/admin_server/storage/mongo/mongo.go
> +	ctx, cancel = context.WithTimeout(context.Background(), DefaultConnectionTimeout)
i actually tested this, the prev cancels are still registered and called
https://go.dev/play/p/IasYHqv6G5J

2022-07-21 00:16 UTC, mimir-d commented on cmds/admin_server/storage/storage.go
>  	StoreLog(Log) error
please post a project issue for this, to reference in the future PR

2022-07-21 00:16 UTC, mimir-d commented on tests/integ/admin_server/getlogs_test.go
> +		continueRetrieve = continueRetrieve && retrieveAll && (int64(result.Count)-int64((currentPage)*(*query.PageSize)) > 0)
i think this should just be
contRetrieve = retrieveAll && (we still have pages)

2022-07-21 00:16 UTC, mimir-d commented on tests/integ/admin_server/getlogs_test.go
> +func equalResults(t *testing.T, expected []mongoStorage.Log, actual []storage.Log) {
```suggestion
func assertEqualResults(t *testing.T, expected []mongoStorage.Log, actual []storage.Log) {
```

2022-07-21 09:00 UTC, mahmednabil109 commented on cmds/admin_server/server/server.go
> +	if query.PageSize == nil {
I am doing it in mongo `GetLog`. Now I see the problem of coupling the two schemas.

2022-07-21 09:03 UTC, mahmednabil109 commented on tests/integ/admin_server/getlogs_test.go
> +	t.Run("no-paging", func(t *testing.T) {
first of all, I don't want to retrieve all the logs in these two cases, and in the 'no-paging' case I need to check that the page number is 0, and the 'no-filtering' I need to check that the pageSize is the MaxPageSize.

2022-07-21 09:21 UTC, mahmednabil109 commented on cmds/admin_server/storage/storage.go
>  	StoreLog(Log) error
I submitted the issue.

2022-07-21 10:28 UTC, mimir-d commented on cmds/admin_server/server/server.go
> +	if query.PageSize == nil {
it should be done here; the max page size is a rest api concept, not a storage one

2022-07-21 10:29 UTC, mimir-d commented on tests/integ/admin_server/getlogs_test.go
> +	t.Run("no-paging", func(t *testing.T) {
ok, sounds reasonable. it was just that i see some duplicated code between these. you can keep them separate

2022-07-21 17:05 UTC, mimir-d commented on cmds/admin_server/storage/mongo/mongo.go
> +	if *query.PageSize < uint(pageSize) {
what @rihter007 wrote is still present in the last version of code. the mongo storage GetLogs may be called from somewhere else (not the rest api entry), which may not have ensured that those pointers are valid. And youre dereferencing them without checking

2022-07-21 17:06 UTC, mimir-d commented on cmds/admin_server/storage/mongo/mongo.go
> +		fmt.Fprintf(os.Stderr, "Error while performing count query: %v", err)
resolving in favor of #104

2022-07-21 17:07 UTC, mimir-d commented on cmds/admin_server/storage/mongo/mongo.go
> +			Value: bson.M{"$gte": primitive.NewDateTimeFromTime(startTime)},
if you want to do it later, post an issue and reference it here

2022-07-21 17:11 UTC, mimir-d commented
there's still a couple of comments above to address; either as a reply or in code changes

2022-07-22 10:46 UTC, mahmednabil109 commented on cmds/admin_server/storage/mongo/mongo.go
> +			Value: bson.M{"$gte": primitive.NewDateTimeFromTime(startTime)},
i will read more about the mongo db indexes, and i will resolve it in the next PR. #106

2022-07-22 13:58 UTC, mimir-d commented on cmds/admin_server/storage/mongo/mongo.go
> +			Value: bson.M{"$gte": primitive.NewDateTimeFromTime(startTime)},
forgot to reference here, it is #106

2022-07-22 14:02 UTC, mimir-d commented on tests/integ/admin_server/logendpoint_test.go
> +	ctx, cancel := context.WithTimeout(context.Background(), time.Duration(*flagTimeout)*time.Second)
https://pkg.go.dev/flag#Duration

2022-07-22 14:42 UTC, mimir-d approved these changes

2022-07-22 14:43 UTC, mimir-d commented
@rihter007 the issues you posted were either resolved or deferred thru issues

2022-07-22 14:43 UTC, merged