Init frontend infrastructer
linuxboot/contest pull request #107
Opened 2022-07-22 14:36 UTC by mahmednabil109

- configure webpack & dev server
- configure typescript for react

Signed-off-by: Mohamed Abokammer <mahmednabil109@gmail.com>

2022-07-22 15:06 UTC, xaionaro commented on cmds/admin_server/frontend/src/App.tsx
> +    return <h1>Context is not Contest</h1>
:D

2022-07-25 12:33 UTC, mimir-d requested changes

2022-07-25 12:33 UTC, mimir-d commented on cmds/admin_server/frontend/.babelrc
> +{
please move this to the webpack config

2022-07-25 12:33 UTC, mimir-d commented on .gitignore
> +**/node_modules/
make a new .gitignore in cmds/admin_server for this

2022-07-25 12:33 UTC, mimir-d commented on cmds/admin_server/frontend/package.json
> +    "typescript": "^4.7.4"
this is a devdep

2022-07-25 12:33 UTC, mimir-d commented on cmds/admin_server/frontend/package.json
> +  "license": "ISC",
MIT

2022-07-25 12:33 UTC, mimir-d commented on cmds/admin_server/frontend/package.json
> +  "name": "frontend",
please rename to "ui" (and the folder as well)

2022-07-25 12:33 UTC, mimir-d commented on cmds/admin_server/frontend/src/App.tsx
> +    return <h1>Context is not Contest</h1>
:laughing:

2022-07-25 12:33 UTC, mimir-d commented on cmds/admin_server/frontend/public/index.html
> +    <title>Contest Debugging Tool</title>
nicer
```
<title>
    <%= htmlWebpackPlugin.options.title %>
</title>
```

2022-07-25 12:33 UTC, mimir-d commented on cmds/admin_server/frontend/.prettierrc
> +{
youre not using this (not ref as devdep in package.json) and if you want it, add as a key to package.json rather than free file

2022-07-25 12:33 UTC, mimir-d commented on cmds/admin_server/frontend/webpack.config.js
> +                test: /\.(js|jsx)$/,
this shouldnt be needed at all

2022-07-25 12:33 UTC, mimir-d commented on cmds/admin_server/frontend/styles/App.scss
> +h1 {
why is the filename capitalized?

2022-07-25 12:33 UTC, mimir-d commented on cmds/admin_server/frontend/styles/App.scss
> +    text-align: center;
you sure you want all h1s on the whole site centered?

2022-07-25 12:33 UTC, mimir-d commented on cmds/admin_server/frontend/webpack.config.js
> +                test: /\.(ts|tsx)$/,
nit; fancier `\.tsx?$`

2022-07-25 12:33 UTC, mimir-d commented on cmds/admin_server/frontend/src/App.tsx
> +export default App
`;` at end of lines

2022-07-25 13:16 UTC, mahmednabil109 commented on .gitignore
> +**/node_modules/
okay

2022-07-25 13:19 UTC, mahmednabil109 commented on cmds/admin_server/frontend/.prettierrc
> +{
it's used by the editor itself. okay.

2022-07-25 13:20 UTC, mahmednabil109 commented on cmds/admin_server/frontend/styles/App.scss
> +h1 {
it's just for the this PR, i will change it with css styles of the table

2022-07-25 13:22 UTC, mahmednabil109 commented on cmds/admin_server/frontend/styles/App.scss
> +    text-align: center;
it's just for this PR, i will change it with the style of the table.

2022-07-25 14:54 UTC, mimir-d commented on cmds/admin_server/frontend/.prettierrc
> +{
what editor though? there is no reference to an editor in this codebase. if it's "your editor", then you can either have a  local override for yourself, or make it explicit by adding to packages.json

2022-07-25 14:56 UTC, mimir-d commented on cmds/admin_server/frontend/styles/App.scss
> +h1 {
convention is fine, just without the caps. keep all filenames lower caps and underscored, despite the naming reqs for react components

2022-07-25 15:06 UTC, mahmednabil109 commented on cmds/admin_server/frontend/.prettierrc
> +{
vscode - i think other editors uses it too -, i added it as a key in the package.json

2022-07-26 14:37 UTC, mimir-d approved these changes

2022-07-26 14:37 UTC, merged