Add job ID to query struct
linuxboot/contest pull request #110
Opened 2022-07-27 10:32 UTC by mahmednabil109

jobID must be added to query in order to be used in filtering entries in the database

Signed-off-by: Mohamed Abokammer <mahmednabil109@gmail.com>

2022-07-27 13:40 UTC, mimir-d requested changes

2022-07-27 13:40 UTC, mimir-d commented on tests/integ/admin_server/getlogs_test.go
> +			q.Set("jobId", fmt.Sprint(*query.JobID))
nit; this works, but for clarity/future safety, let's do strconv.FormatUint

2022-07-27 13:40 UTC, mimir-d commented on cmds/admin_server/server/server.go
> +	JobID     *uint64    `form:"jobId"`
didnt see this before; can we have snake_case for the rest api query? no reason in particular, it's a bit closer to json

2022-07-27 14:09 UTC, mimir-d requested changes

2022-07-27 14:09 UTC, mimir-d commented on tests/integ/admin_server/logendpoint_test.go
> +func submitLog(addr string, log server.Log) error {
for this one, we should have it in a different PR. on this same topic, i see there's a storage.Log and a server.Log; the server one has json annotations, but are those needed on the storage model? if not, remove them in the same PR with this line

2022-07-27 14:20 UTC, mahmednabil109 commented on tests/integ/admin_server/logendpoint_test.go
> +func submitLog(addr string, log server.Log) error {
the json annotation is needed for serialization in both storage, and http response.

2022-07-29 13:57 UTC, mimir-d commented on tests/integ/admin_server/logendpoint_test.go
> +func submitLog(addr string, log server.Log) error {
done in #111

2022-07-29 14:08 UTC, mimir-d commented
pease rebase on top of #111 (or main)

2022-07-29 14:19 UTC, mahmednabil109 commented on tests/integ/admin_server/logendpoint_test.go
> +func submitLog(addr string, log server.Log) error {
rebased, but ig this will wait for #117

2022-08-01 13:36 UTC, mimir-d approved these changes

2022-08-01 13:36 UTC, merged