Add logs table ui
linuxboot/contest pull request #113
Opened 2022-07-28 16:39 UTC by mahmednabil109

- Add table component in admin server ui
- Use superagent to fetch logs from the backend api

Signed-off-by: Mohamed Abokammer <mahmednabil109@gmail.com>

2022-08-01 17:34 UTC, mahmednabil109 commented
waiting for #119.

2022-08-02 11:35 UTC, mimir-d requested changes

2022-08-02 11:35 UTC, mimir-d commented on cmds/admin_server/ui/src/app.tsx
> +            console.log(err);
this isnt enough; add an error component (overlay probably or toast) or add a todo+issue and addressin another PR

2022-08-02 11:35 UTC, mimir-d commented on cmds/admin_server/ui/src/app.tsx
> +                page: page - 1,
the value "1" is presentational, so actually "add 1" in the presentation layer (in jsx)

2022-08-02 11:35 UTC, mimir-d commented on cmds/admin_server/ui/src/app.tsx
> +            setCount(result.count);
nit; this makes for multiple renders (if you move to a class based component, you can do setState just once  with both)

2022-08-02 11:35 UTC, mimir-d commented on cmds/admin_server/ui/src/app.tsx
> +            <div className="input-group">
nit; would be nice to add a screenshot with ui to the PR; makes it easier to read this jsx

2022-08-02 11:35 UTC, mimir-d commented on cmds/admin_server/ui/src/app.tsx
> +                    <Cell style={{ padding: '2px' }} dataKey="job_id" />
nit; would be nicer to be consistent, you started to use css rules, so keep using that instead of inline style

2022-08-02 11:35 UTC, mimir-d commented on cmds/admin_server/ui/src/app.tsx
> +        if (!isMounted.current) {
i get what this does, but why is it used? why discard the first render

2022-08-02 11:35 UTC, mimir-d commented on cmds/admin_server/ui/src/app.tsx
> +        updateLogsTable();
nit; perf issue, this generates an extra render each time something changes in state

2022-08-02 11:35 UTC, mimir-d commented on cmds/admin_server/ui/src/app.tsx
> +        } else setPage(1);
note, the fact that you need to do this is an artifact of the design of having data pulls as a side-effect.
for example, a reader might say "you can just use setPage(1)" instead of setting it conditionally and this wouldnt actually work because the side-effect isnt triggered. but it's not obvious why it wouldnt work

2022-08-02 11:35 UTC, mimir-d commented on cmds/admin_server/ui/src/app.tsx
> +        } else setPage(1);
you should reconsider the data pulling mechanism (and in this process remove the extra render implied by the use effect)

2022-08-02 11:45 UTC, mahmednabil109 commented on cmds/admin_server/ui/src/app.tsx
> +        if (!isMounted.current) {
to avoid making requests in the first render (most probably it will not be needed)

2022-08-02 11:46 UTC, mahmednabil109 commented on cmds/admin_server/ui/src/app.tsx
> +        updateLogsTable();
if __something__ refs to __page or limit__ (deps list), isn't that required to render a new data whenever page or limit states change ?

2022-08-02 11:50 UTC, mahmednabil109 commented on cmds/admin_server/server/server.go
> +	r.GET("/", redirectTo(url.URL{Path: "/app"}))
yes, i said that it will be not possible as gin declares a wildcard match for static files (`/*filepath`) if i moved the webapp to `/` then every thing will match with the static FS.

2022-08-02 11:51 UTC, mahmednabil109 commented on cmds/admin_server/server/server.go
> +	r.GET("/", redirectTo(url.URL{Path: "/app"}))
but i will move the rest api to `/api/v1`

2022-08-02 14:33 UTC, mahmednabil109 commented on cmds/admin_server/ui/src/app.tsx
> +            setCount(result.count);
does it? i remember that react 18 useState hook batches the updates

2022-08-02 15:24 UTC, mahmednabil109 commented on cmds/admin_server/ui/src/index.tsx
> +import 'rsuite/dist/rsuite.min.css';
> if there's a sass version for this,

unfortunately, there is only `less`

2022-08-03 10:01 UTC, mimir-d commented on cmds/admin_server/ui/src/app.tsx
> +            setCount(result.count);
you are correct; my react knowledge is older than v18

2022-08-03 10:03 UTC, mimir-d commented on cmds/admin_server/ui/src/app.tsx
> +        if (!isMounted.current) {
yeah, not needed; i see you removed it anyway

2022-08-03 10:08 UTC, mimir-d commented on cmds/admin_server/ui/src/app.tsx
> +        updateLogsTable();
you shouldnt have hidden dependencies like that, if you wanna change the page, you should set state for both page and contents, otherwise this happens in 2 steps (the initial change, and reaction to change). i see you fixed this currently.
On a sidenote, in LogTable you have a group of set logs+count+page+pagesize; i think you can group all of those in a single object and set it (because theyre not updated individually from what i see). Though that's not a reason for me not to accept the pr.

2022-08-03 10:11 UTC, mimir-d commented on cmds/admin_server/ui/src/search_logs/log_table/log_table.scss
> +        display: block !important;
using !important is usually a sign of something wrong. i'll skip over it this time

2022-08-03 10:14 UTC, mimir-d commented on cmds/admin_server/ui/src/search_logs/log_table/log_table.tsx
> +}: LogTableProps) {
nit, sometimes it's ok to extract fields, sometimes not. in this case i think this reduces readability. I dont know, for example, in updateLogsTable() (which could be just update() now or getData()) that "logLevels" is not a local variable. It would be better with "props.logLevels"

2022-08-03 10:16 UTC, mimir-d approved these changes

2022-08-03 10:17 UTC, merged