Feature/variables teststep
linuxboot/contest pull request #124
Opened 2022-08-09 14:26 UTC by rihter007

2022-08-09 22:22 UTC, mimir-d requested changes

2022-08-09 22:22 UTC, mimir-d commented on pkg/runner/test_steps_variables.go
> +func (sva *stepVariablesAccessor) AddRaw(tgtID string, name string, inRaw json.RawMessage) error {
you already have the Add(in interface{}); should be able to use that directly
```
if raw, ok := in.(json.RawMessage); ok {
    sva.tsv.Add(raw)
    return
}
```

2022-08-09 22:22 UTC, mimir-d commented on plugins/teststeps/variables/variables.go
> +package variables
please add docs md (see exec plugin for example))

2022-08-09 22:22 UTC, mimir-d commented on tests/e2e/e2e_test.go
> +func (ts *E2ETestSuite) startTask(taskFile string) types.JobID {
consistency in naming concepts

```suggestion
func (ts *E2ETestSuite) startJob(descriptorFile string) types.JobID {
```

2022-08-09 22:22 UTC, mimir-d commented on plugins/teststeps/variables/variables.go
> +			if err := stepsVars.AddRaw(target.ID, name, ps[0].RawMessage); err != nil {
so... whats the usage for this? renaming strings?

2022-08-09 23:41 UTC, rihter007 commented on plugins/teststeps/variables/variables.go
> +			if err := stepsVars.AddRaw(target.ID, name, ps[0].RawMessage); err != nil {
Do you mean the plugin in general or that specific loop?

2022-08-15 12:08 UTC, mimir-d commented on plugins/teststeps/variables/variables.go
> +			if err := stepsVars.AddRaw(target.ID, name, ps[0].RawMessage); err != nil {
the plugin; i see it takes in strings, with possible interpolations, and outputs the result as a single string; this could be done just as well in the consumers of these output vars here. unless there's something im not seeing

2022-08-17 12:56 UTC, rihter007 commented on plugins/teststeps/variables/variables.go
> +			if err := stepsVars.AddRaw(target.ID, name, ps[0].RawMessage); err != nil {
You are correct, it is not a super-useful plugin. One can just directly put these strings in consuming plugins as you mentioned.
I made it because of three reasons:
- it shows an example of how to use StepVariables and is also used in e2e test. ConTest has a number of "example" plugins like echo or randecho.
- it allows to make constants that will be reused in multiple places. For example: if two or more plugins should consume **the same parameter**, one can use this plugin instead of copy-pasting.
- on the future if step variables will have more options of being used (not just via parameters expanding) it could become a handy way to share variables

2022-08-26 00:24 UTC, mimir-d approved these changes

2022-08-26 00:25 UTC, mimir-d commented
the added doc file makes it much more clear what the plugin is about

2022-08-26 18:46 UTC, merged