Use batch logic to push logs
linuxboot/contest pull request #129
Opened 2022-08-15 10:31 UTC by mahmednabil109

Signed-off-by: Mohamed Abokammer <mahmednabil109@gmail.com>

2022-08-15 13:58 UTC, rihter007 commented on cmds/admin_server/storage/storage.go
> +	StoreLogs(ctx xcontext.Context, batch LogBatch) error
why do we need a LogBatch type?  Why not to just []Log?

2022-08-15 13:58 UTC, xaionaro commented on cmds/admin_server/server/server.go
> +}
Quick question: should this function be thread-safe?

2022-08-15 13:59 UTC, mahmednabil109 commented on cmds/admin_server/storage/storage.go
> +	StoreLogs(ctx xcontext.Context, batch LogBatch) error
to make it easy to add any metadata -in the futuer- along with the batch.

2022-08-15 14:02 UTC, mahmednabil109 commented on cmds/admin_server/server/server.go
> +}
I can't see why, the logBatch will not be shared across threads.

2022-08-15 14:28 UTC, rihter007 commented on cmds/admin_server/server/server.go
>  	r.POST("/log", rh.addLog)
I also expected that batching will apply to /log API, so the local server will hold sending the logs further. @mimir-d what do you think?

2022-08-15 14:28 UTC, rihter007 commented on pkg/loggerhook/httphook.go
> +	BatchRetryDelay   = 100 * time.Millisecond
Having good defaults is great, but I would also add overriding with command line parameters

2022-08-15 14:28 UTC, rihter007 commented on pkg/loggerhook/httphook.go
> +	hh.logBatch = make([]server.Log, 0)
in context with retry hh.logBatch will be 0 after first try and if it failed, they will be lost by the time of the second try

2022-08-15 14:28 UTC, rihter007 commented on pkg/loggerhook/httphook.go
> +			hh.batchMux.Lock()
As far as I understand logHandler works in a single goroutine, so if batch variables are not used elsewhere, having mutexes is not needed.

Also block everything during retries (that have Sleep) is not great, probably a good way is to either launch a goroutine that will try to post or to add retries in the current loop. Probably retrying at the next tick is ok.

2022-08-15 15:30 UTC, mahmednabil109 commented on pkg/loggerhook/httphook.go
> +	BatchRetryDelay   = 100 * time.Millisecond
yeah, i guess it will be better to add it in another PR.

2022-08-15 15:32 UTC, mahmednabil109 commented on pkg/loggerhook/httphook.go
> +	BatchRetryDelay   = 100 * time.Millisecond
will be added, #130

2022-08-15 15:33 UTC, mahmednabil109 commented on cmds/admin_server/server/server.go
>  	r.POST("/log", rh.addLog)
I can merge the two endpoints, by always sending an array of logs.

2022-08-15 16:22 UTC, rihter007 commented on cmds/admin_server/server/server.go
>  	r.POST("/log", rh.addLog)
It is ok to have two separate, but inside use batch for everything

2022-08-15 16:37 UTC, rihter007 commented on pkg/loggerhook/httphook.go
> +					fmt.Fprintf(os.Stderr, "Send Batch faild: %v", err)
nit

"... failEd: %v"

2022-08-15 16:37 UTC, rihter007 commented on pkg/loggerhook/httphook.go
> +				hh.logBatch = make([]server.Log, 0)
nit

Just hh.logBatch = nil

2022-08-15 16:40 UTC, rihter007 commented on pkg/loggerhook/httphook.go
> +				}
I guess we should also do hh.logBatch = nil here? Maybe this operation can be put inside postBatch()

2022-08-15 16:41 UTC, rihter007 commented on pkg/loggerhook/httphook.go
> +				hh.sendTicker.Reset(BatchSendFreq)
I see that the Ticker always has BatchSendFreq timeout or did I miss something?

2022-08-15 16:42 UTC, rihter007 submitted a review, later dismissed
Overall looks good, just left some final comments

2022-08-15 16:47 UTC, mahmednabil109 commented on pkg/loggerhook/httphook.go
> +				hh.sendTicker.Reset(BatchSendFreq)
i didn't get the question, but here I reset the ticker if I already send a batch to give the logger sometime to collect logs and avoid ticking on empty batch slice.

2022-08-15 19:49 UTC, rihter007 commented on pkg/loggerhook/httphook.go
> +				hh.sendTicker.Reset(BatchSendFreq)
Ah, ok, makes sense!

2022-08-15 19:50 UTC, rihter007 submitted a review, later dismissed
`LGTM!

2022-08-16 01:06 UTC, mimir-d requested changes
the mandatory change is to address non-empty current batch when closing; rest are recommendations

2022-08-16 01:06 UTC, mimir-d commented on pkg/loggerhook/httphook.go
> +					break
so if unable to post a batch, it just gives up? maybe figure out if this is a temporary error and if you can retry

2022-08-16 01:06 UTC, mimir-d commented on pkg/loggerhook/httphook.go
> +	hh.logBatch = nil
it isnt clear from the api (and no docs) that this postBatch method also clears the current queue. id say to add a batch type and a method that clearly says "sendBatchAndReset" or something like that

2022-08-16 01:06 UTC, mimir-d commented on pkg/loggerhook/httphook.go
>  			fmt.Fprintf(os.Stderr, "Closing http logger")
what if there's still stuff in the queue here?

2022-08-16 01:08 UTC, mimir-d commented on cmds/admin_server/server/server.go
>  	r.POST("/log", rh.addLog)
it's fine to change the endpoint now, but keep in mind that this is a breaking change and wont work after this starts to be used

2022-08-16 01:08 UTC, mimir-d commented on cmds/admin_server/storage/storage.go
> +	StoreLogs(ctx xcontext.Context, batch LogBatch) error
valid point, but what kind of metadata do you expect?

2022-08-16 10:22 UTC, mahmednabil109 commented on cmds/admin_server/storage/mongo/mongo.go
> +	var monogLogs []interface{}
yes, but insertMany takes `[]interface{}` and it can't convert from `[]log` to that type.

2022-08-16 10:23 UTC, mahmednabil109 commented on pkg/loggerhook/httphook.go
> +					break
No, if there is an error, it will try to send in the next tick, as i will not reset the batch.

2022-08-16 11:20 UTC, mimir-d commented on pkg/loggerhook/httphook.go
> +					break
correct; the break sees the select first. thought it was breaking the for

2022-08-16 11:23 UTC, mimir-d commented on pkg/loggerhook/httphook.go
> +	hh.logBatch = nil
prob wasnt clear; the send method is on the batch type not on the hook (this also avoids using the batch type incorrectly as the reset would only be done in the send and not exposed to consumers)

2022-08-16 11:24 UTC, mimir-d commented on pkg/loggerhook/httphook.go
> +func (b *Batch) Get() []server.Log {
these 2 methods (get/reset) disappear when you move the send method here

2022-08-16 11:47 UTC, rihter007 approved these changes

2022-08-16 13:00 UTC, mimir-d commented on pkg/loggerhook/httphook.go
> +	addr string
this isnt realy a property of the batch, but i can ignore this; you shouldve had it as a param in send

2022-08-16 13:02 UTC, mimir-d approved these changes

2022-08-16 13:02 UTC, merged