Add project endpoint to admin server
linuxboot/contest pull request #139
Opened 2022-08-22 15:41 UTC by mahmednabil109

- add project/job endpoints to query tasks by project name

Signed-off-by: Mohamed Abokammer <mahmednabil109@gmail.com>

2022-08-22 18:27 UTC, xaionaro requested changes
LGTM. But please address the comment tagged as "**error**" :)

2022-08-22 18:27 UTC, xaionaro commented on cmds/admin_server/server/server.go
> +	jobdb   jobdb.DB
**nit**

`jobDB` -- usually we use mixed caps for multiple words. See https://github.com/golang/go/wiki/CodeReviewComments#initialisms ; example: `appID` (not `appid`).

2022-08-22 18:27 UTC, xaionaro commented on tests/integ/admin_server/group_jobs_by_project_test.go
> +	if _, err := db.Exec(safesql.New("DELETE FROM jobs")); err != nil {
**just thinking out loud (ignore me)**

I guess semantically you meant not to delete jobs, but to empty the table, right? (see the difference between `DELETE` and `TRUNCATE` here: https://www.geeksforgeeks.org/difference-between-delete-and-truncate/)

2022-08-22 18:27 UTC, xaionaro commented on tests/integ/admin_server/group_jobs_by_project_test.go
> +		return nil, err
**nit**

Since there are multiple sources of error in this function, it would be nice to wrap them and add an additional description to all of them (to be able to traceback by the error message itself).

2022-08-22 18:27 UTC, xaionaro commented on cmds/admin_server/jobdb/rdbms/rdbms.go
> +	res := []jobdb.Project{}
**question**

Out of curiosity. Below I see that you usually start slices with a nil value. While here you decided to get an empty preallocated slice beforehand. Why is the difference?

2022-08-22 18:27 UTC, xaionaro commented on cmds/admin_server/jobdb/db.go
> +	GetProjects(ctx xcontext.Context, text string) ([]Project, error)
**nit**

s/`text`/`tagSubstring`/

2022-08-22 18:27 UTC, xaionaro commented on cmds/admin_server/jobdb/db.go
> +}
**Just thinking out loud (ignore me)**

Non-flexible queries API :)

2022-08-22 18:27 UTC, xaionaro commented on cmds/admin_server/jobdb/rdbms/rdbms.go
> +	projectStmt = `SELECT tag, COUNT(tag) FROM job_tags Where tag LIKE CONCAT('%%',?,'%%') GROUP BY tag`
**warning**

This is a bit confusing. The query looks like you select "tags" (not "project"-s). So why is it called "projectStmt"? And why `tag` value is assigned to `&project.Name`? Would be nice to get more clarity in what is "tag" and what is "project".

2022-08-22 18:27 UTC, xaionaro commented on cmds/admin_server/jobdb/db.go
> +	JobID        uint64
**warning**

Why the type is not `types.JobID`?

2022-08-22 18:27 UTC, xaionaro commented on cmds/admin_server/jobdb/rdbms/rdbms.go
> +	projectStmt = `SELECT tag, COUNT(tag) FROM job_tags Where tag LIKE CONCAT('%%',?,'%%') GROUP BY tag`
**warning**

It is required to add a comment to the function, which checks tag names, that `%` and `_` are forbidden to use because of this query.

2022-08-22 18:27 UTC, xaionaro commented on cmds/admin_server/jobdb/rdbms/rdbms.go
> +	projectStmt = `SELECT tag, COUNT(tag) FROM job_tags Where tag LIKE CONCAT('%%',?,'%%') GROUP BY tag`
**error**

I see that in the regexp responsible for checking tags, symbol `_` is permitted. While it has special meaning for `LIKE`.

2022-08-22 18:36 UTC, rihter007 commented on cmds/admin_server/jobdb/rdbms/rdbms.go
> +		_ = rows.Close()
nit

Mb log the error?

2022-08-22 18:39 UTC, rihter007 commented on cmds/admin_server/jobdb/rdbms/rdbms.go
> +	if err := job.CheckTags([]string{projectName}, true); err != nil {
nit

true is for internal tags, I guess we should not allow it

2022-08-22 18:44 UTC, rihter007 commented on cmds/admin_server/jobdb/rdbms/rdbms.go
> +	projectStmt = `SELECT tag, COUNT(tag) FROM job_tags Where tag LIKE CONCAT('%%',?,'%%') GROUP BY tag`
I agree with the @xaionaro comments.
It is not clear how "text" will be used to find tags. I would either use regexp: https://dev.mysql.com/doc/refman/8.0/en/regexp.html or something simple like prefix.

2022-08-22 18:46 UTC, rihter007 commented on cmds/admin_server/jobdb/rdbms/rdbms.go
> +	projectStmt = `SELECT tag, COUNT(tag) FROM job_tags Where tag LIKE CONCAT('%%',?,'%%') GROUP BY tag`
If we check using CheckTags, then tagPrefix should be good enough

2022-08-23 13:16 UTC, mahmednabil109 commented on cmds/admin_server/jobdb/rdbms/rdbms.go
> +	res := []jobdb.Project{}
I though it would be better to return an empty slice rather than nil for empty query result. Ig I should unify it in the api in another pr.

2022-08-23 13:25 UTC, mahmednabil109 commented on cmds/admin_server/jobdb/rdbms/rdbms.go
> +	projectStmt = `SELECT tag, COUNT(tag) FROM job_tags Where tag LIKE CONCAT('%%',?,'%%') GROUP BY tag`
> This is a bit confusing. The query looks like you select "tags" (not "project"-s)

tags and projects are the same thing. basically HW team groups tasks by project/platform thru tags hence the name. But after thinking it's better to  name it tag in the code.

2022-08-23 13:49 UTC, mahmednabil109 commented on cmds/admin_server/jobdb/rdbms/rdbms.go
> +	res := []jobdb.Project{}
I thought it would be better to return an empty slice rather than nil in case of empty query result. ig i should open another pr to unify that in the code.

2022-08-23 13:51 UTC, mahmednabil109 commented on cmds/admin_server/jobdb/db.go
> +}
it should fit the current requested feature and i think it can be easily extended.

2022-08-24 09:17 UTC, rihter007 commented on cmds/admin_server/jobdb/rdbms/rdbms.go
> +	rows, err := r.db.Query(safesql.New(tagsStmt), tagSubstring)
nit

I like how you called argument tagSubstring, but now it is in REGEXP which allows to do much more than substring + you add .*

If using regexp meta symbols is allowed, I would drop job.CheckTags. In the worst case nothing will be selected, which seems ok to me.

2022-08-24 09:19 UTC, rihter007 submitted a review, later dismissed
LGTM, but probably job.CheckTags should be dropped in GetTags method

2022-08-24 13:22 UTC, xaionaro commented on cmds/admin_server/jobdb/rdbms/rdbms.go
> +	res := []jobdb.Project{}
> I though it would be better to return an empty slice rather than nil for empty query result.

Sounds reasonable.

2022-08-24 13:31 UTC, xaionaro submitted a review, later dismissed
I agree with @rihter007: LGTM, the concerns we had were addressed; the only new concern is that the SQL statement now uses "REGEXP" (and the `Substring` is not misleading)

2022-08-24 16:06 UTC, mimir-d requested changes
requesting changes for the naming of db-related packages.

Meanwhile, what is the design leading to here? I'm seeing a `/tag` endpoint added, returning info about all possible job tags and jobs by tags but the PR description talks about projects.
Would be nice if you could explain how this "tag service" is useful.

2022-08-24 18:08 UTC, mimir-d commented
> Meanwhile, what is the design leading to here? 

Seems there was a thread above with this. We should continue there.

2022-08-24 18:12 UTC, mimir-d commented on cmds/admin_server/jobdb/rdbms/rdbms.go
> +	projectStmt = `SELECT tag, COUNT(tag) FROM job_tags Where tag LIKE CONCAT('%%',?,'%%') GROUP BY tag`
> tags and projects are the same thing

well, no. Tags are just pieces of strings attached to the job. They can be anything.
You might implement the "project" concept with tags, but that doesnt mean they're identical. Also, what happens if the job has multiple tags? Do all of them get treated as projects?

2022-08-24 18:13 UTC, mimir-d commented on cmds/admin_server/jobdb/db.go
> +}
@xaionaro bit more detail? is what way is it inflexible? (note, i have my own interpretation of that based on the "DB" name, but i want to hear your opinion)

2022-08-24 18:16 UTC, mimir-d commented on cmds/admin_server/jobdb/rdbms/rdbms.go
> +	res := []jobdb.Project{}
> return an empty slice rather than nil for empty query result

return where? this is in database code by the looks of it, and for all intents and purposes a nil slice is the same as an empty slice.

If youre actually referring to the json serialization later on, why? This code doesnt have any idea about the json-related clients. That aspect needs to be dealt with in the client code where json is made. It's not a DB requirement.

2022-08-24 18:46 UTC, xaionaro commented on cmds/admin_server/jobdb/db.go
> +	ErrBadJobTag = errors.New("job tag must follow this regex [a-zA-Z0-9_-]")
Yeah, single source of truth would be nice.

2022-08-24 18:47 UTC, xaionaro commented on cmds/admin_server/jobdb/rdbms/rdbms.go
> +	_ "github.com/go-sql-driver/mysql"
BTW, this kind of side-effects better to put into `main`, usually.

2022-08-24 18:49 UTC, xaionaro commented on cmds/admin_server/jobdb/rdbms/rdbms.go
> +	res := []jobdb.Project{}
> return where? 

I understand: from `GetTags`. I understood @mahmednabil109 's point is to separate "unknown/undefined" (nil) from "empty" (empty slice) in the returned value.

2022-08-24 18:52 UTC, xaionaro commented on cmds/admin_server/jobdb/db.go
> +}
Well. I used to see basically query languages. Not just few hardcoded narrow-focused queries instead.

2022-08-25 13:36 UTC, mahmednabil109 commented on cmds/admin_server/jobdb/rdbms/rdbms.go
> +	_ "github.com/go-sql-driver/mysql"
I am no't that familiar with safesql, but ig it's the normal way to register a sql driver for safesql to use. it's the same here https://github.com/linuxboot/contest/blob/main/plugins/storage/rdbms/init.go#L22. I will add a comment to clarify it abit.

2022-08-25 14:06 UTC, mahmednabil109 commented on cmds/admin_server/jobdb/rdbms/rdbms.go
> +	tagsStmt = `SELECT tag, COUNT(tag) FROM job_tags Where tag REGEXP CONCAT('.*',?,'.*') GROUP BY tag`
I first used `like` but there was some allowed characters in the tag name that is special in like clause such as `_`, then ilya suggested using regex and then we can benefit from the regex patterns by allowing queries like `tagpattern=\d+`.

2022-08-25 14:27 UTC, mimir-d commented on cmds/admin_server/jobdb/rdbms/rdbms.go
> +	res := []jobdb.Project{}
> just a bit of extra precision about meaning of returned values of the function

hardly relevant in this case, in my view

2022-08-25 15:23 UTC, xaionaro commented on cmds/admin_server/jobdb/rdbms/rdbms.go
> +	res := []jobdb.Project{}
I kinda like this precision, if that what the author meant. Does it have downsides? It just provides an additional bit of information (so you may differentiate "undefined" from "empty"). You may not do that as well.

2022-08-25 16:43 UTC, mahmednabil109 commented on cmds/admin_server/jobdb/db.go
> +}
> There is even no way to just request a specific project.

the project is a bunch of jobs so using `GetJobs` you can get a specific project by name.

2022-08-25 16:54 UTC, mahmednabil109 commented on cmds/admin_server/jobdb/rdbms/rdbms.go
> +type RDBMS struct {
`jobdb` pkg is dealing with querying jobs and group them by tags. and RBMS here refers to the tybe of that db that stores the jobs.

2022-08-31 13:25 UTC, mimir-d requested changes

2022-08-31 13:25 UTC, mimir-d commented on cmds/admin_server/job/sql/stroage.go
> +	jobstorage "github.com/linuxboot/contest/cmds/admin_server/job"
this jobstorage name wouldve been ok for something like `admin_server/storage/job` or `admin_server/job/storage`, but in this case it doesnt make sense. The fact that you have a storage.go in that package folder, doesnt automatically make it "storage".

2022-08-31 13:25 UTC, mimir-d commented on cmds/admin_server/job/sql/stroage.go
> +// GetTags returns project/tags that has a tag matches tagPattern
this code here really has no concept of "project". youre just handling tags. if you wanna make this about projects, make it explicit in the naming of the functions, structs, etc
```suggestion
// GetTags returns tags that has a tag matches tagPattern
```

2022-08-31 13:25 UTC, mimir-d commented on cmds/admin_server/job/storage.go
> +// Tag contains metadata about jobs under a given tag (project)
as i said before, `tag` is not `project`. you can implement the projects concept with tags, but theyre not identical
```suggestion
// Tag contains metadata about jobs under a given tag
```

2022-08-31 13:25 UTC, mimir-d commented on cmds/admin_server/main.go
> +	flagLogBDURI = flagSet.String("dbURI", "mongodb://localhost:27017", "Logs Database URI")
this rename (and doc change) was not necessary; the database here *currently* contains logs, but it may not be only that in the future; it's a database for the ui needs

2022-08-31 13:25 UTC, mimir-d commented on cmds/admin_server/main.go
> +	if *flagContestDBURI != "" {
should this be optional though? kinda complicates stuff in server.go as well

2022-08-31 13:25 UTC, mimir-d commented on cmds/admin_server/server/server.go
> +func toServerTag(t *jobStorage.Tag) Tag {
makes more sense to have `fromStorageTag` here, because the main model is the server one, not the storage. if you had this func next to the storage model, it would be the other way around

2022-08-31 13:25 UTC, mimir-d commented on cmds/admin_server/server/server.go
> +	ReporterName *string     `json:"reporter_name"`
a reader of the json object that gets produced from this would have no idea what `Data` is, for example.
to make this more self-documented, do
```go
type report struct {
    name string `json`
    success bool `json`
    time
    data
}
type Job struct {
    JobID types.JobID `json job_id`
    Report *report `json final_report` // nullable only here
}
```

2022-08-31 13:25 UTC, mimir-d commented on cmds/admin_server/server/server.go
> +	var query struct {
good; not poluting the package namespace with local structs that dont get used anywhere else

2022-08-31 13:25 UTC, mimir-d commented on cmds/admin_server/server/server.go
> +	res, err := r.jobDB.GetTags(xcontext.Background(), query.Text)
timeout

2022-08-31 13:25 UTC, mimir-d commented on cmds/admin_server/server/server.go
> +	res, err := r.jobDB.GetJobs(xcontext.Background(), projectName)
timeout

2022-08-31 13:25 UTC, mimir-d commented on cmds/admin_server/server/server.go
> +	jobs := make([]Job, 0, len(res))
seems that you want a function for array of storage.Job rather than a single object

2022-08-31 13:25 UTC, mimir-d commented on cmds/admin_server/server/server.go
> +		c.JSON(http.StatusInternalServerError, gin.H{"status": "err", "msg": "error while getting the projects"})
youre using this
```
{ "status": "err", "msg": "something" }
```
quite a lot. shouldnt you have some facility to make this error response?

2022-08-31 13:27 UTC, mimir-d commented on cmds/admin_server/jobdb/db.go
> +}
@xaionaro close/resolve if ready

2022-08-31 13:28 UTC, mimir-d commented on cmds/admin_server/jobdb/rdbms/rdbms.go
> +	res := []jobdb.Project{}
that'd be fine, but i get the feeling it was related to the json serialization, and seeing "nulls" there

2022-08-31 13:28 UTC, mimir-d commented
there's some discussion still pending in top unresolved comments @mahmednabil109

2022-08-31 14:34 UTC, mahmednabil109 commented on cmds/admin_server/server/server.go
> +		c.JSON(http.StatusInternalServerError, gin.H{"status": "err", "msg": "error while getting the projects"})
could you please give an example ?

2022-08-31 15:46 UTC, mahmednabil109 commented on cmds/admin_server/jobdb/rdbms/rdbms.go
> +	projectStmt = `SELECT tag, COUNT(tag) FROM job_tags Where tag LIKE CONCAT('%%',?,'%%') GROUP BY tag`
> Do all of them get treated as projects?

Yes, I guess the definition of the project does not contradict with this, from the point of view of the project it should contain some jobs that are related.

2022-08-31 16:05 UTC, mahmednabil109 commented on cmds/admin_server/jobdb/rdbms/rdbms.go
> +	res := []jobdb.Project{}
it was to differentiate between nil & empty results - although it was originated from the api responses, it's the same concept there; when sending `\log?tagPattern=\d` it makes more sense to return `[]` rather that `undefined`.

2022-08-31 21:32 UTC, mimir-d commented on cmds/admin_server/server/server.go
> +		c.JSON(http.StatusInternalServerError, gin.H{"status": "err", "msg": "error while getting the projects"})
```
func makeRestErr(format string, args ...any) gin.H {
    return gin.H{"status":"err", "msg": format_args}
}
```

2022-08-31 21:34 UTC, mimir-d commented on cmds/admin_server/jobdb/rdbms/rdbms.go
> +	res := []jobdb.Project{}
> when sending `\log?tagPattern=\d`

what does this mean exactly? are you talking about the rest api layer or storage?

2022-08-31 21:38 UTC, mimir-d commented on cmds/admin_server/jobdb/rdbms/rdbms.go
> +	projectStmt = `SELECT tag, COUNT(tag) FROM job_tags Where tag LIKE CONCAT('%%',?,'%%') GROUP BY tag`
> I guess the definition of the project does not contradict with this

it does, tags are even used internally for other things, which are not semantically "projects". so if i were you, id think of some namespacing concept for these tags to make them "projects" or use that `/tags` endpoint in a creative name so you dont have the problem.
eg. if a descriptor has tags "test, short, intel" does that mean it's in the "short" project? only "intel" would be a project here.

2022-08-31 21:40 UTC, mimir-d commented on cmds/admin_server/job/sql/stroage.go
> +package sql
i wasnt talking about "sql", the directory. I was talking about file name. "stroage". You still have the problem.

2022-08-31 21:41 UTC, mimir-d commented on cmds/admin_server/job/sql/stroage.go
> +	jobstorage "github.com/linuxboot/contest/cmds/admin_server/job"
comment on this? i dont see changes in new push

2022-09-01 10:09 UTC, mahmednabil109 commented on cmds/admin_server/jobdb/rdbms/rdbms.go
> +	res := []jobdb.Project{}
here i was talking about the rest api, but it's the same for the storage.

2022-09-01 11:20 UTC, mahmednabil109 commented on cmds/admin_server/server/server.go
> +		c.JSON(http.StatusInternalServerError, gin.H{"status": "err", "msg": "error while getting the projects"})
note that in the docker file golang 1.16 is being used. `any` requires golang version 1.18 at least.

2022-09-04 22:07 UTC, mimir-d commented on cmds/admin_server/jobdb/rdbms/rdbms.go
> +	res := []jobdb.Project{}
right, @xaionaro, seems I was right when i said (this wasn't about precision)
> but i get the feeling it was related to the json serialization

@mahmednabil109 again, pay attention to the difference betweeen db models and restapi models. You were using a db model to serialize json, hence the confusion between nil and empty arrays. The storage layer *does not* require to return non-nil empty arrays and in general in go it is idiomatic to use a nil for empty array.

2022-09-04 22:07 UTC, mimir-d commented on cmds/admin_server/jobdb/rdbms/rdbms.go
> +	res := []jobdb.Project{}
closing since the `fromStorage...` methods address this

2022-09-04 22:09 UTC, mimir-d requested changes
return for broken linter; seems good to go otherwise

2022-09-04 22:11 UTC, mimir-d commented on cmds/admin_server/jobdb/rdbms/rdbms.go
> +	projectStmt = `SELECT tag, COUNT(tag) FROM job_tags Where tag LIKE CONCAT('%%',?,'%%') GROUP BY tag`
as discussed offline, this PR will just address tags. Projects will be an UI concept for specially crafted tags (not in scope here)

2022-09-05 09:46 UTC, mahmednabil109 commented on .github/workflows/tests.yml
> +          go version
i added this to make sure of the version used, i will remove it.

2022-09-05 09:47 UTC, mahmednabil109 commented on .github/workflows/tests.yml
>          run: ./run_lint.sh
I update the go version in another PR, i think the problem should be solved after a rebase.

2022-09-05 15:05 UTC, mimir-d approved these changes

2022-09-05 15:06 UTC, merged