Add UI components to render tags
linuxboot/contest pull request #149
Opened 2022-09-07 14:54 UTC by mahmednabil109

- add react router to switch between searching logs and tags
- add checkbox to search projects (tags with special prefix)

- add project/job endpoints to query tasks by project name

Signed-off-by: Mohamed Abokammer <mahmednabil109@gmail.com>

2022-09-07 20:22 UTC, mimir-d commented
i rerun the failing test and it's still failing. you should have a look at it

2022-09-07 20:22 UTC, mimir-d commented
what does the UI look like? missing screenshot

2022-09-07 20:45 UTC, mimir-d requested changes

2022-09-07 20:45 UTC, mimir-d commented on tests/e2e/test-simple.yaml
> +
please remove this file from the PR since it has no relevant changes

2022-09-07 20:45 UTC, mimir-d commented on cmds/admin_server/ui/package.json
> +    "name": "ui",
what's the change here? tabs to spaces? please remove this from PR if changes are just whitespace

2022-09-07 20:45 UTC, mimir-d commented on cmds/admin_server/ui/src/api/tags.ts
> +    console.log(result);
no console logs in final prod code

2022-09-07 20:45 UTC, mimir-d commented on cmds/admin_server/ui/src/api/tags.ts
> +    report: Report;
shouldnt this be?
```suggestion
    report: Report | null;
```

2022-09-07 20:45 UTC, mimir-d commented on cmds/admin_server/ui/src/jobs/jobs.tsx
> +import DateCell from '../search_logs/log_table/date_cell/date_cell';
this import is not ok. if you need that date_cell, you should pull all of that in a different place/component so that both log_table and jobs here can use it

2022-09-07 20:45 UTC, mimir-d commented on cmds/admin_server/ui/src/jobs/jobs.tsx
> +        (async () => {
could you explain how this works? youre making an async lambda, immediately calling it, so it's not awaited and then the setLoading(false) is done before the data is available. That's what i see. Am i wrong?

2022-09-07 20:45 UTC, mimir-d commented on cmds/admin_server/ui/src/jobs/jobs.tsx
> +                console.log(result, name);
no console logs

2022-09-07 20:45 UTC, mimir-d commented on cmds/admin_server/ui/src/jobs/jobs.tsx
> +                console.log(err);
this should be an error popup or something

2022-09-07 20:45 UTC, mimir-d commented on cmds/admin_server/ui/src/search_logs/log_table/date_cell/date_cell.tsx
> +const recAccess = (rowData: any, dataKey?: string): any => {
i get that you wanna be generic here but youre inside the DateCell component and are only using this func to get a Data type field
```suggestion
function resolveDatakey(rowData: any, dataKey?: string): Date {
```

2022-09-07 20:45 UTC, mimir-d commented on cmds/admin_server/ui/src/search_tags/search_tags.tsx
> +            if (!tagPattern.startsWith('project_'))
should extract this `project_` prefix into a const

2022-09-07 20:45 UTC, mimir-d commented on cmds/admin_server/ui/src/search_tags/tags_grid/tags_grid.tsx
> +            console.log(result);
no console logs

2022-09-08 10:09 UTC, mahmednabil109 commented on cmds/admin_server/ui/src/jobs/jobs.tsx
> +        (async () => {
right, it should be inside the lambda.

2022-09-08 11:20 UTC, mimir-d commented on cmds/admin_server/ui/src/search_tags/tags_grid/tags_grid.tsx
> +            console.log(err);
you missed some

2022-09-08 15:07 UTC, mimir-d commented on cmds/admin_server/server/server.go
> +		if strings.HasSuffix(c.Param("filepath"), ".js") {
what about css stuff? does it work for that?

2022-09-08 15:10 UTC, mahmednabil109 commented on cmds/admin_server/server/server.go
> +		if strings.HasSuffix(c.Param("filepath"), ".js") {
webpack outputs only index.html and bundle.js and the css is embedded into the js file

2022-09-08 17:07 UTC, mimir-d commented on cmds/admin_server/server/server.go
> +		if strings.HasSuffix(c.Param("filepath"), ".js") {
well ok, that's good enough for now. doesnt do well with caching, but this isnt a big deployment anyway

2022-09-08 17:30 UTC, mimir-d approved these changes

2022-09-08 17:30 UTC, merged