Add support for cleanup steps
linuxboot/contest pull request #163
Opened 2023-05-17 15:22 UTC by vjt

This implements feature request #143.

Missing:

* handling the pause event while in cleanup steps - *DONE*
* handling errors in cleanup steps - *DONE* by ignoring them
* unit tests - *DONE*
* integration tests - *DONE*

2023-05-17 21:57 UTC, mimir-d commented
youve a broken test; 
what should i understand from the "missing" section above? option 1. you'd like this PR merged and then you add others separately (in which case, i need to check if this one is functionally complete for what it does). or option 2. this a WIP PR and you'll add more commits to it

2023-05-18 08:11 UTC, vjt commented
> youve a broken test;

working on fixing that

> what should i understand from the "missing" section above? option 1. you'd like this PR merged and then you add others separately (in which case, i need to check if this one is functionally complete for what it does). or option 2. this a WIP PR and you'll add more commits to it

sorry, I wrote that in a hurry. this is a WIP PR and I'll add more commits to it. I'd like your review on what it has been done so far, whether it is reasonable or not, and your insights on the missing items :-)

Thank you!

2023-05-19 11:06 UTC, vjt reviewed
Adding some comments where I think we still need work

2023-05-19 11:06 UTC, vjt commented on pkg/runner/job_runner.go
> +			}
I don't think this will work, because we are returning the runner state of the cleanup steps runner, and when resuming this state is going to be fed to the test steps runner.

We'd need a new way to signal that we were in cleanup steps, and skip the execution of tests steps and jump directly to the cleanup steps.

2023-05-19 11:06 UTC, vjt commented on pkg/runner/job_runner.go
> +		testRunnerState, targetsResults, stepOutputs, err := testRunner.Run(
I am returning `stepOutputs` here that is the steps variable registry to feed it back when calling the cleanup steps runner, so that any variable collected during test runs is available also in the cleanup steps.

I am not sure however if that is the proper way of doing this :-)

2023-05-19 11:06 UTC, vjt commented on tests/integ/jobmanager/common.go
> +{[JOBID 1 IntegrationTest: steps 0 goodbye_world][Target{ID: "id1"} TargetOut]}
these two lines should actually have `IntegrationTest: cleanup` instead of `IntegrationTest: steps` but I think this can be left as a subsequent improvement

2023-05-23 01:44 UTC, mimir-d requested changes

2023-05-23 01:44 UTC, mimir-d commented on pkg/jobmanager/bundles.go
> +func validateNoDuplicateLables(testStepBundles []test.TestStepBundle, cleanupStepBundles []test.TestStepBundle) error {
typo
```suggestion
func validateNoDuplicateLabels(testStepBundles []test.TestStepBundle, cleanupStepBundles []test.TestStepBundle) error {
```

2023-05-23 01:44 UTC, mimir-d commented on pkg/jobmanager/bundles.go
>  	labels := make(map[string]bool)
did you know that if you use `struct{}` instead of `bool`, the map does not take any space for values? and just turns into a set, in terms of memory consumption

2023-05-23 01:44 UTC, mimir-d commented on pkg/jobmanager/job.go
> +			cleanupName = thisTestStepsDescriptors.CleanupName
wondering if we really need a `CleanupName`. the test name makes sense, cleanup.. not so much to me

2023-05-23 01:44 UTC, mimir-d commented on pkg/jobmanager/job.go
> +		if err := validateNoDuplicateLables(bundleTest, bundleCleanup); err != nil {
you can remove duplication here (and an extra loop in func) by saying
```suggestion
		if err := validateNoDuplicateLables(append(bundleTest, bundleCleanup...)); err != nil {
```

2023-05-23 01:44 UTC, mimir-d commented on pkg/pluginregistry/bundles.go
> +		cp             interface{}
`cp`? 

it's better if we dont follow this old C style, generally speaking. ok in short loops or short funcs. this is neither

2023-05-23 01:44 UTC, mimir-d commented on pkg/runner/job_runner.go
> +		testRunnerState, targetsResults, stepOutputs, err := testRunner.Run(
it may be possible to lift it from testrunner and give it as input here; if that's too much, im ok with this current form

2023-05-23 01:44 UTC, mimir-d commented on pkg/runner/job_runner.go
> +				NewTestStepEventsEmitterFactory(jr.storageEngineVault, j.ID, runID, t.Name, testAttempt),
this is probably not a good idea; the events emitted in cleanup should be separated from test events;
see if there's some aspect to differentiate between them (you can run a test job where both test and cleanup steps emit events; cmd/exec plugin should be simplest to get the stdout event and check in the output status json)

2023-05-23 01:44 UTC, mimir-d commented on pkg/runner/job_runner.go
> +			}
correct; you can probably make that difference by aggregating this resume state into a bigger object.
if you look at the signature `([]*target.Target, json.RawMessage, bool, error)`, it shows that the 2nd param is a json.rawmessage

so you could do, 
1. if interrupted in test steps, make another object `struct State { teststate: json.Raw, cleanupstate: json.Raw}` and return `targets, State{ teststate: testRunnerState, cleanupstate: nil }, succeed, err` (though you probably also need to move that `succeed` and `err` inside the struct
2. if interrupted in cleanup, the `State.cleanupstate` wont be nil; you may need to select on some aspect there whether test steps need to rerun at all on resume (because if we got interrupted in cleanup it means that the test has finished)

this is obviously a breaking change for the state resume format, so it'll need a json version increase (it's somewhere up where the json gets serialized). and you'll need to change it's ingestion as well

think of this in the lines of "if i get descheduled right here, how do i make the func reentrant" (kinda like how async works in python/rust)

2023-05-23 01:44 UTC, mimir-d commented on pkg/runner/test_runner.go
> +	onVariableAdded := func(tgtID string, stepLabel string, name string, value json.RawMessage) {
```suggestion
	onStepOutputAdded := func(tgtID string, stepLabel string, name string, value json.RawMessage) {
```

this was supposed to be named "step outputs" in the first place

2023-05-23 01:44 UTC, mimir-d commented on pkg/runner/test_runner.go
> +		stepOutputs = stepOutputs_
ehh?

just dont define a new var? `stepOutputs, err = newTestStepsVariables...`

2023-05-23 01:44 UTC, mimir-d commented on pkg/runner/test_runner.go
> +	if stepOutputs == nil {
kinda not pretty; as i was saying above, see if you can lift this

2023-05-23 01:44 UTC, mimir-d commented on pkg/test/step.go
> +	CleanupName  string
mentioned prev; i dont think we need a name for the cleanup; it's part of the test and the test has a name already

2023-05-23 01:44 UTC, mimir-d commented on tests/integ/jobmanager/common.go
> +{[JOBID 1 IntegrationTest: steps 0 goodbye_world][Target{ID: "id1"} TargetOut]}
no no, this is an actual problem. i was saying above, if we cant discriminate between events emitted by the test steps vs events from the cleanup, it makes for a mixed mess

2023-05-25 22:26 UTC, mimir-d commented
please also change this to merge into `develop` instead of `main`

2023-05-26 11:16 UTC, vjt commented on pkg/runner/job_runner.go
> +			}
I am going through the route of adding another `json.RawMessage` attribute to the [`PauseEventPayload` struct](https://github.com/linuxboot/contest/blob/main/pkg/job/events.go#L97), calling it `CleanupRunnerState`. If that is set, it means we were in cleanup steps, so test steps are skipped. :-)

What do you think? This looks simper and should not require structure changes to the test-level `resumeStateStructVersion`.

Another point is that, in the end, this is job-level information, not test-level.

Thanks!

2023-05-26 11:32 UTC, vjt commented on tests/integ/jobmanager/common.go
> +{[JOBID 1 IntegrationTest: steps 0 goodbye_world][Target{ID: "id1"} TargetOut]}
OK, found, it was a trivial change in the TestStepEventsEmitter call, in which I was passing the test name and not the cleanup name.

2023-05-26 11:33 UTC, vjt commented on pkg/jobmanager/job.go
> +			cleanupName = thisTestStepsDescriptors.CleanupName
the cleanupName is used to emit events with a different prefix

2023-05-26 11:38 UTC, vjt commented on pkg/pluginregistry/bundles.go
> +		cp             interface{}
OK, fixed also the `fp` -> `fetchParameters`

2023-05-26 11:41 UTC, vjt commented on pkg/test/step.go
> +	CleanupName  string
as mentioned, we want a way to distinguish the events emitted by the test with the ones emitted by the cleanup :-)

2023-05-26 11:45 UTC, vjt commented on pkg/runner/test_runner.go
> +	if stepOutputs == nil {
I think I can do that, but in a subsequent changeset, to not further complicate this one

2023-05-26 12:23 UTC, vjt commented on pkg/runner/job_runner.go
> +				NewTestStepEventsEmitterFactory(jr.storageEngineVault, j.ID, runID, t.Name, testAttempt),
we can distinguish them easily by using the Cleanupname instead of the test Name. What do you think?

2023-05-26 16:05 UTC, mimir-d requested changes
not many changes, but one of the tests is failing

2023-05-26 16:05 UTC, mimir-d commented on plugins/storage/rdbms/events.go
> +	if testEventQuery.TestNames != nil {
nit; go doesnt make much of a difference between an empty slice and a nil slice; you can iterate on both
however, your check here only looks for nil. would be better as `if len(...) > 0`

2023-05-26 16:05 UTC, mimir-d commented on pkg/runner/job_runner_test.go
> +{[1 1 SimpleTest: CLEANUP 0 test_cleanup_step][Target{ID: "T1"} TargetIn]}
should there be extra spaces here? thought the discussion result was "%s:CLEANUP"

2023-05-26 16:07 UTC, mimir-d commented on pkg/runner/job_runner.go
> +			}
ok with this design, as discussed in call

2023-05-26 17:06 UTC, vjt commented on pkg/runner/job_runner_test.go
> +{[1 1 SimpleTest: CLEANUP 0 test_cleanup_step][Target{ID: "T1"} TargetIn]}
I've decided to add the extra space because of [this test](https://github.com/vjt/contest/blob/feature/143/tests/integ/jobmanager/common.go#L635-L636) as `:` is not a special char and users can use it. What do you think?

2023-05-26 17:19 UTC, mimir-d commented on pkg/runner/job_runner_test.go
> +{[1 1 SimpleTest: CLEANUP 0 test_cleanup_step][Target{ID: "T1"} TargetIn]}
right; no good character, at the end of the day it doesnt really matter what that is as long as it's not too confusing. feel free to keep as is, or without the space, or another separator like `@%#`

2023-05-27 13:39 UTC, vjt commented on pkg/runner/job_runner_test.go
> +{[1 1 SimpleTest: CLEANUP 0 test_cleanup_step][Target{ID: "T1"} TargetIn]}
I might end up with ` [CLEANUP]`

2023-05-27 15:06 UTC, vjt commented
Tests finally pass! [0f7af7c](https://github.com/linuxboot/contest/pull/163/commits/0f7af7cce78f8c973fb461f0b7866fa1ef1f2639) was particularly painful, because I was thinking to make a change affecting only test code, but in reality the code that fetches from storages is the same across tests and prod. Anyway, the change looks reasonable to me.

Cheers

2023-05-27 20:02 UTC, mimir-d commented
thanks for working on this

2023-05-27 20:02 UTC, mimir-d approved these changes

2023-05-27 20:02 UTC, merged