Migrating the whole project from xcontext to go-belt.
linuxboot/contest pull request #164
Opened 2023-05-20 00:07 UTC by xaionaro

# What

Here I do substitution of `xcontext` to [`go-belt`](https://github.com/facebookincubator/go-belt#approach-contextual-logger) and [`signallers`](https://github.com/linuxboot/contest/tree/migrate/go_belt/pkg/signaller). The APIs are mostly compatible, so this was a pretty mechanistic stupid job (could mostly be done with `sed`).

Caveats:
* `xcontext` binds together three different things: observability API, context and signals (currently used to propagate `Pause` signal across the application). And it is problematic to make the migration of observability API and signals separately, because if I migrate one thing, it breaks another thing. So I migrate them together in one commit.
* In `xcontext` both `Cancel` and `Pause` as processed by the same handler. But after migration `Cancel` is processed by standard `context` API, while `Pause` is processed by additional signal-handler. Because of that it is now no unified API between these two.

---

# Why

TLDR: **`xcontext` is succeeded by `go-belt`.** `xcontext` existed for some time, there was gathered the feedback and in result `go-belt` is a better version of similar ideas.

## More details

The previous design had few very serious problems:
* It was basically a God Object, which binds together multiple things (see the first point in `Caveats` above) and is not scalable horizontally (the amount of observability tools are limited).
* It required to propagate everywhere a custom implementation of `context.Context`, which causes different inconveniences with necessity to type-cast and do other similar stuff. Also the custom context type started to propagate to public APIs which never was the intention (public APIs should always use only the standard context).

There were also other known (less serious) problems, and in `go-belt` all that is solved.

---

# How

The PR consists of 4 commits:
* [[pkg/signaller] Add a package to handle Pause signal](https://github.com/linuxboot/contest/commit/5554d583b90861cfe53e06594e7dbb092f070777). This commit re-implements the signal propagator for `Pause` (though it can propagate other signals as well).
* [Migrate from xcontext to go-belt and signaller](https://github.com/linuxboot/contest/commit/1d5340976f8cc4c46168bb34b09de38a67521efb). This comment switches the code of contest for both observability and signals from `xcontext` to `go-belt` and `signaller` accordingly. This is mostly mechanistic change, which stupidly changes the code to an equivalent.
* [Delete xcontext](https://github.com/linuxboot/contest/commit/9b520a9d603768dadb2bdb79cbf843ae8f59119e). In this commit package `xcontext` is deleted (package `perf` is kept and moved out of `xcontext`).
* [Add verbosity to diagnose mis-signaling](https://github.com/linuxboot/contest/commit/5d30af4509882aacc2f2b57fd772ae94ffaf7c2d). Contains changes I needed to diagnose and fix the second commit.

2023-05-20 01:00 UTC, mimir-d commented
this is gonna take a while to review

2023-05-22 13:17 UTC, xaionaro commented
I've switched the base from `main` to `develop`, since the PR contains API-breaking changes.

2023-05-23 02:46 UTC, mimir-d requested changes
only reviewed first commit so far

2023-05-23 02:46 UTC, mimir-d commented on pkg/signaller/broadcast_signal.go
> +package signaller
might be a better idea to name this package `signaling`. naming a package after a type can lead to stuttering or taking up useful names in code (because we have collisions between pkg names and variables in go...)

2023-05-23 02:46 UTC, mimir-d commented on pkg/signaller/broadcast_signal.go
> +type broadcastSignalT struct{}
this is an error? very confusing from the type name. also what's with the `T` at the end?

2023-05-23 02:46 UTC, mimir-d commented on pkg/signaller/ctx_key.go
> +type signallerCtxKeyT struct{}
does this really need a whole new file?

2023-05-23 02:46 UTC, mimir-d commented on pkg/signaller/signaller.go
> +type signaller struct {
both forms are accepted, but can you can this to signaler? i think ive seen this one used more in programming stuff usually

also noticed inconsistency with IsSignaledWith, which doesnt have double ll

2023-05-23 02:46 UTC, mimir-d commented on pkg/signaller/is_signaled_with.go
> +	if len(signals) == 0 && (len(s.receivedSignals) != 0) {
```suggestion
	if len(signals) == 0 && len(s.receivedSignals) != 0 {
```

2023-05-23 02:46 UTC, mimir-d commented on pkg/signaller/is_signaled_with.go
> +	for _, receivedErr := range s.receivedSignals {
is this func meant to be called with a lock held? should be specified in a doc

2023-05-23 02:46 UTC, mimir-d commented on pkg/signaller/received_signals.go
> +func (s *signaller) ReceivedSignals() []error {
it's not ideal to split a single type over multiple files; makes reading very difficult

2023-05-23 02:46 UTC, mimir-d commented on pkg/signaller/signaller.go
> +	children map[*signaller]struct{}
nice usage of nil-sized `struct{}`

2023-05-23 02:46 UTC, mimir-d commented on pkg/signaller/signaller.go
> +func withSignaller(ctx context.Context) (*signaller, context.Context) {
these funcs usually return ctx first

2023-05-23 02:46 UTC, mimir-d commented on pkg/signaller/signaller.go
> +		delete(parent.children, s)
so these relationships are kept around until program termination?

2023-05-23 02:46 UTC, mimir-d commented on pkg/signaller/until.go
> +		return openChan
id keep this `openChan` in this same file, where it's used. hunting for it in the code is not easy. same with the closed one (init can be defined anywhere in the module and you dont need it for anything else, so it can be moved from the main pkg file)

2023-05-23 02:46 UTC, mimir-d commented on pkg/signaller/signaller_test.go
> +func TestRace(t *testing.T) {
where is the race here exactly?
i see a pretty serial execution; goroutine starts, main gets blocked in `<-readyToSelect`. then goroutine unblocks on `<-startSelect` and the signal is read from `ch`
this shows me that the signal is buffered rather than a race. what am i missing?

2023-05-23 02:46 UTC, mimir-d commented on pkg/signaller/signaller_test.go
> +	ctx, pauseFunc := WithSignal(context.Background(), unitTestCustomSignal0)
`defer pauseFunc()` just for general code etiquette

2023-05-23 02:46 UTC, mimir-d commented on pkg/signaller/signaller_test.go
> +	<-Until(ctx2, unitTestCustomSignal0)
might wanna add a `select <-time.After` to these chan reads in case it hangs, so it doesnt also hang the unittest indefinitely

2023-05-23 02:46 UTC, mimir-d commented on pkg/signaller/with_signal.go
> +	if s.signalChans[signal] == nil {
this also looks like it's meant to be called with lock held; should specify in a doc (or make the lock reentrant and use it everywhere)

2023-05-23 02:46 UTC, mimir-d commented on pkg/signaller/with_signal.go
> +// WithSignal is similar to context.WithCancel, but it does not close the context
`close the context`? you mean `cancel the context`?

2023-05-23 02:46 UTC, mimir-d commented on pkg/signaller/with_signal.go
> +// and sends a signal to the Context which use observable using Until and IsSignaledWith
```suggestion
// and sends a signal to the Context which can be observed using Until and IsSignaledWith
```

2023-05-23 02:46 UTC, mimir-d commented on pkg/signaller/with_signal.go
> +func (s *signaller) signalFunc(signal error, moreSignals ...error) context.CancelFunc {
why does this need to be a method of its own; cant we just have `func() { s.signal(...) }` 2 lines above?

2023-05-23 02:46 UTC, mimir-d commented on pkg/signals/paused.go
> +var Paused = error(pausedT{})
docs? this is a public symbol

2023-05-23 02:46 UTC, mimir-d commented on pkg/signals/paused.go
> +func (pausedT) Error() string { return "job is paused" }
technically not a job, but whole server

2023-05-23 03:28 UTC, mimir-d requested changes
2nd commit reviewed; some styling changes and docs requested

2023-05-23 03:28 UTC, mimir-d commented on SPAG.md
> +* A **cancellation** may come in (`ctx.Done()`). This means the job is cancelled or failed entirely and nothing can be done to save it. Plugins SHOULD immediately cease all actions and return. Plugin
type in go context is with single `l`
`var Canceled = errors.New("context canceled")`

2023-05-23 03:28 UTC, mimir-d commented on SPAG.md
> +* A **pause request** may come in. This means the contest server wants to restart. Not all plugins can support this easily, you can choose to ignore the pause request and continue as normal, however
not sure is `signals` is enough of a pkg for just one 1-line type. maybe put that in signaling as well

2023-05-23 03:28 UTC, mimir-d commented on SPAG.md
> +* Successful pause is communicated by returning `Paused` from the Run method. If the plugin was responsible for any targets at the time, any other return value (including `nil`) will be considered a
would be better to use fully qualified name as above

2023-05-23 03:28 UTC, mimir-d commented on cmds/admin_server/job/rdb/rdb.go
> +				logger.FromCtx(ctx).Errorf("error while closing the rows reader: %w", err)
generally speaking, it would be cleaner to have this at the beginning of the func as
`log := logger.FromCtx(ctx)`
and then use
`log.Errorf(...)`

what happens if this logger ctx key was not set? in a sense this is not that materially different from xcontext, since the logger is still tied to ctx

2023-05-23 03:28 UTC, mimir-d commented on cmds/admin_server/main.go
> +	flagSet.Var(&logLevel, "logLevel", "A log level, possible values: debug, info, warning, error, panic, fatal")
tested this? im not sure how this deserializes from string

2023-05-23 03:28 UTC, mimir-d commented on cmds/admin_server/server/server.go
> +	ctx = logger.CtxWithLogger(ctx, r.log)
im curious; if we make the assumption that the logger is mutable, any child ctx could modify the logger for parent ctxs as well, right?

so the only way to get correct behavior is that the logger object is immutable (not a thing in go, but just limit the public api that mutates). is it the case that this ctx value logger is immutable once set?

2023-05-23 03:28 UTC, mimir-d commented on pkg/api/api.go
> +		Context:  beltctx.WithField(ctx, "api_method", "stop"),
is the semantic the same here? i get a feeling this `WithField` here for xcontext meant that it was outputted as a logger field and im not sure it does the same with beltctx

2023-05-23 03:28 UTC, mimir-d commented on pkg/loggerhook/httphook.go
> +func (hh *HttpHook) ProcessLogEntry(entry *logger.Entry) bool {
seems you changed this to go-belt logger, so the comment is now wrong

2023-05-23 03:28 UTC, mimir-d commented on pkg/loggerhook/httphook.go
> +	entry.Fields.ForEachField(func(f *field.Field) bool {
there is no find by key method?

2023-05-23 03:28 UTC, mimir-d commented on pkg/loggerhook/httphook.go
> +			if hh.batch.Size() > 0 {
if you include this `if` in `doFlush`, it removes more lines here and is a noop for the usage in `if hh.batch.Count() > hh.cfg.MaxBatchCount || hh.batch.Size() > uint64(hh.cfg.MaxBatchSize)`

2023-05-23 03:28 UTC, mimir-d commented on pkg/runner/test_runner_test.go
> +	defer beltctx.Flush(ctx)
are these really equivalent? flush with cancel?

2023-05-23 03:29 UTC, mimir-d commented
since this touches state resume in a lot of places, id like to see a test with that. maybe a step with sleep 30, sigint the server and resume

that would also show if there's any changes in the log output

2023-05-23 03:33 UTC, mimir-d reviewed
reviewed last 2 commits; looks ok

2023-05-23 03:33 UTC, mimir-d commented on pkg/runner/test_runner.go
> +				logger.FromCtx(ctx).Tracef("got event from stepsErrorsCh")
well, if youre gonna write a log line here, write the `runErr` as well

2023-05-23 03:33 UTC, mimir-d commented on pkg/jobmanager/start.go
> +		errmon.ObserveErrorCtx(ctx, _err)
does this `errmon` have any effect?

2023-05-23 12:54 UTC, xaionaro commented on pkg/signaller/broadcast_signal.go
> +type broadcastSignalT struct{}
> this is an error?

I frankly have no opinion on which type a signal should have. By inertia (after `context.Context.Done()`) I use interface `error`. But it feels like some opportunities are missed by continuing this tradition. I decided this is not that important to think hard about this right away (could be fixed afterwards).

> very confusing from the type name. also what's with the `T` at the end?

Basically this is a one-time-use type to define a variable below. And `T` is a signifier that this is a **t**ype. Any preference on naming here?

2023-05-23 12:59 UTC, xaionaro commented on pkg/signaller/ctx_key.go
> +type signallerCtxKeyT struct{}
It does not fit any existing file. I can use `signaller.go` as a common collector of all misfits, but... does an additional file cause any harm? I have no opinion here, feel free to suggest just what you'd like to see.

---

**UPDATE**: Reworked the whole thing. Now everything is in one file.

2023-05-23 13:04 UTC, xaionaro commented on pkg/signaller/is_signaled_with.go
> +	for _, receivedErr := range s.receivedSignals {
Reworked the whole thing. No more lockers.

2023-05-23 13:10 UTC, xaionaro commented on pkg/signaller/received_signals.go
> +func (s *signaller) ReceivedSignals() []error {
I have no strong opinion.

Moved all `signaller` code into one file.

2023-05-23 13:15 UTC, xaionaro commented on pkg/signaller/signaller.go
> +		delete(parent.children, s)
No.

The idea is that the `*signaller` is stored in the `context.Context`, so if the `Context` is not used anymore (and not reachable anymore) then `*signaller` is also not reachable anymore and thus the finalizer will be called and will automatically remove the relationship as part of GC.

2023-05-23 13:16 UTC, xaionaro commented on pkg/signaller/signaller.go
> +		delete(parent.children, s)
In the original code it was a Finalizer for `context.Context`. When copy&pasting I fixed to `*signaller` and broke the whole logic. Good catch.

2023-05-23 13:55 UTC, xaionaro commented on pkg/signaller/until.go
> +		return openChan
Fixed.

2023-05-23 14:04 UTC, xaionaro commented on pkg/signaller/signaller_test.go
> +func TestRace(t *testing.T) {
Does not feel important enough to spend time remembering the whole context how this function was written in the first place (in xcontext). So I just deleted it.

2023-05-23 15:26 UTC, xaionaro commented on SPAG.md
> +* A **pause request** may come in. This means the contest server wants to restart. Not all plugins can support this easily, you can choose to ignore the pause request and continue as normal, however
`signaling` was supposed to be a generic package, which does not know anything about `contest`. And `signals` was supposed to be a set of signals specific to `contest`.

2023-05-23 15:28 UTC, xaionaro commented
I've started to redesign `signaling`: there was a known and shameful problem I had no time to fix in `xcontext`, and it correlates with some of the feedback. So I guess I finally need to find time to redesign the thing and fix that :)

Will publish today-tomorrow.

2023-05-23 21:39 UTC, xaionaro commented on pkg/signaller/broadcast_signal.go
> +package signaller
Fixed.

2023-05-23 21:39 UTC, xaionaro commented on pkg/signaller/signaller.go
> +type signaller struct {
Fixed.

2023-05-23 21:39 UTC, xaionaro commented on pkg/signaller/is_signaled_with.go
> +	if len(signals) == 0 && (len(s.receivedSignals) != 0) {
Fixed.

2023-05-23 21:39 UTC, xaionaro commented on pkg/signaller/signaller.go
> +func withSignaller(ctx context.Context) (*signaller, context.Context) {
Fixed.

2023-05-23 21:40 UTC, xaionaro commented on pkg/signaller/signaller.go
> +		delete(parent.children, s)
Reworked the whole thing. Less functionality, but much less complexity and no need to play with Finalizers.

2023-05-23 21:42 UTC, xaionaro commented on pkg/signaller/signaller_test.go
> +	ctx, pauseFunc := WithSignal(context.Background(), unitTestCustomSignal0)
Fixed.

2023-05-23 21:42 UTC, xaionaro commented on pkg/signaller/signaller_test.go
> +	<-Until(ctx2, unitTestCustomSignal0)
Feels kinda wrong. We already have `-timeout` in `go test` for this problem.

2023-05-23 21:43 UTC, xaionaro commented on pkg/signaller/with_signal.go
> +	if s.signalChans[signal] == nil {
Reworked the whole thing. No more lockers.

2023-05-23 21:43 UTC, xaionaro commented on pkg/signaller/with_signal.go
> +// WithSignal is similar to context.WithCancel, but it does not close the context
Changed the wording.

2023-05-23 21:43 UTC, xaionaro commented on pkg/signaller/with_signal.go
> +func (s *signaller) signalFunc(signal error, moreSignals ...error) context.CancelFunc {
Fixed.

2023-05-23 21:44 UTC, xaionaro commented on pkg/signals/paused.go
> +func (pausedT) Error() string { return "job is paused" }
Fixed.

2023-05-23 21:45 UTC, xaionaro commented on pkg/signals/paused.go
> +var Paused = error(pausedT{})
Fixed.

2023-05-23 21:50 UTC, xaionaro commented on SPAG.md
> +* A **cancellation** may come in (`ctx.Done()`). This means the job is cancelled or failed entirely and nothing can be done to save it. Plugins SHOULD immediately cease all actions and return. Plugin
Fixed.

2023-05-23 21:51 UTC, xaionaro commented on SPAG.md
> +* Successful pause is communicated by returning `Paused` from the Run method. If the plugin was responsible for any targets at the time, any other return value (including `nil`) will be considered a
Kinda fixed: I used not fully qualified (`github.com/linuxboot/contest/pkg/signals.Paused`), but the shortened form: `signals.Paused`.

2023-05-23 21:59 UTC, xaionaro commented on cmds/admin_server/job/rdb/rdb.go
> +				logger.FromCtx(ctx).Errorf("error while closing the rows reader: %w", err)
> generally speaking, it would be cleaner to have this at the beginning of the func as `log := logger.FromCtx(ctx)` and then use `log.Errorf(...)`

I mostly used `find ... -exec sed` to make this PR. Personally I do not feel better about doing `log := logger.FromCtx(ctx)` first: because once you obtain a logger it no longer receive information about anything added to the context (like `beltctx.WithField`).

> what happens if this logger ctx key was not set? in a sense this is not that materially different from xcontext, since the logger is still tied to ctx

When one calls `logger.FromCtx(ctx)`,
* It first tries to obtain a logger from `ctx`.
* If fails then it uses the [default Logger](https://github.com/facebookincubator/go-belt/blob/main/tool/logger/belt.go#L20-L32).

2023-05-23 22:03 UTC, xaionaro commented on cmds/admin_server/main.go
> +	flagSet.Var(&logLevel, "logLevel", "A log level, possible values: debug, info, warning, error, panic, fatal")
> tested this?

Yes (though not in contest).

> im not sure how this deserializes from string

The `logLevel` thing implements interface `flag.Value`, and in the end of the day it uses this function: https://github.com/facebookincubator/go-belt/blob/a4b0c08c6bb7df899ccd0868e9e6312a1d977358/tool/logger/types/level.go#L170-L198

2023-05-23 22:07 UTC, xaionaro commented on cmds/admin_server/server/server.go
> +	ctx = logger.CtxWithLogger(ctx, r.log)
> im curious; if we make the assumption that the logger is mutable, any child ctx could modify the logger for parent ctxs as well, right?

No, logger is considered immutable: [there are no mutation methods](https://github.com/facebookincubator/go-belt/blob/main/tool/logger/types/logger.go#L37-L219), only modification-methods derive a new `Logger`, instead of modifying the original.

2023-05-23 22:12 UTC, xaionaro commented on pkg/api/api.go
> +		Context:  beltctx.WithField(ctx, "api_method", "stop"),
The semantic is very close:
* In `xcontext` the `WithField` means to add a structured field to `Logger` and `Tracer`.
* In `go-belt` the `WithField` means to add a structured field to all the `Tool`-s who wants to add this field. And a `Metrics` implementation for `go-belt` adds a field only if a special `FieldProperty` is passed. So effectively this line adds the field to `Logger`, `Tracer`, `ErrorMonitor` and potentially some other tools (but not `Metrics`).

2023-05-23 22:15 UTC, xaionaro commented on pkg/loggerhook/httphook.go
> +func (hh *HttpHook) ProcessLogEntry(entry *logger.Entry) bool {
Fixed.

2023-05-23 22:17 UTC, xaionaro commented on pkg/loggerhook/httphook.go
> +	entry.Fields.ForEachField(func(f *field.Field) bool {
No. The design of this things allows only linear search. So the person who wants to find by key method should suffer :)
Not a strong opinion though.

2023-05-23 22:25 UTC, xaionaro commented on pkg/loggerhook/httphook.go
> +			if hh.batch.Size() > 0 {
Something like this was my initial thought, but the fact we use `.batch.Count()` instead of `.batch.Size()` below stopped me. I decided not to be too smart and keep this PR as stupid as possible.

2023-05-23 22:27 UTC, xaionaro commented on pkg/runner/test_runner_test.go
> +	defer beltctx.Flush(ctx)
Not really, but the test was passing, so I assumed `cancel()` wasn't really needed. And I added `Flush` to make sure the log is output-ed before the application completion. Would you like me to return `cancel()`?

2023-05-23 22:28 UTC, xaionaro commented
> since this touches state resume in a lot of places, id like to see a test with that. maybe a step with sleep 30, sigint the server and resume

I thought we have integration tests, which check this. No?

2023-05-23 22:30 UTC, xaionaro commented on pkg/jobmanager/start.go
> +		errmon.ObserveErrorCtx(ctx, _err)
It should. If no `ErrorMonitor` is setup in the context then it should spew out the errors through the `Logger` (with logging level `Error`). But one may use [Sentry](https://docs.sentry.io/) and/or LogView and/or something-else as the `ErrorMonitor` and get errors aggregated and nice.

2023-05-23 22:32 UTC, xaionaro commented on pkg/runner/test_runner.go
> +				logger.FromCtx(ctx).Tracef("got event from stepsErrorsCh")
Fixed.

2023-05-24 15:03 UTC, xaionaro commented
Commit "[[pkg/signaling] Add a package to handle Pause signal](https://github.com/linuxboot/contest/pull/164/commits/b6ce88ec6bfb1c4fbe82f11a9d8ba48a13414f46)" was rewritten from scratch and requires a full review. In other commits the changes are isolated to minimalistically address the provided feedback.

2023-05-25 13:41 UTC, mimir-d requested changes
some changes requested for first commit; specifically that panic bit

2023-05-25 13:41 UTC, mimir-d commented on pkg/signaling/signaler.go
> +			panic("was never supposed to happen")
id prefer we dont have panics in the code (unless in func main). just killing the whole server, even on good assertions, would decrease reliability overall and increase difficulty in debugging

also, this makes the `return !isOpen` a tautology

2023-05-25 13:41 UTC, mimir-d commented on pkg/signaling/signaler.go
> +type signaler = chan struct{}
nit; a new type is slightly better than an alias here; the make(signaler) will work the same, but it discourages users from making some assumptions

```suggestion
type signaler chan struct{}
```

2023-05-25 13:41 UTC, mimir-d commented on pkg/signaling/signaler.go
> +	signaler, _ := ctx.Value(ctxKey[T]{Signal: signal}).(signaler)
cant wait to see this fail with our version of go. i remember templates were working but not too well

2023-05-25 13:41 UTC, mimir-d commented on pkg/signaling/signaler.go
> +func WithSignal[T Signal](ctx context.Context, signal T) (context.Context, context.CancelFunc) {
i disagree with the usage of `context.CancelFunc` here; it's not semantically correct. you should make a new type `type SignalFunc func()`

2023-05-25 13:41 UTC, mimir-d commented on pkg/signaling/signaler.go
> +	return signaler
would add a comment here saying that `Until` works because if there was no signal defined, the chan would be nil and reading blocks forever; may not be obvious to everyone

2023-05-25 13:51 UTC, mimir-d commented on pkg/signaller/signaller_test.go
> +	ctx, pauseFunc := WithSignal(context.Background(), unitTestCustomSignal0)
sorry, i deleted this comment after i wrote it, but somehow it still ended up here; the defer was in the same sense as cleaning up resources in a ctx.withcancel
```
ctx, cancel := withcancel(ctx)
defer cancel()
...
// later, for whatever reason
cancel()
```

but it doesnt make as much sense for the pausing signaling

2023-05-25 13:52 UTC, mimir-d commented on pkg/signaller/signaller_test.go
> +	<-Until(ctx2, unitTestCustomSignal0)
ok, not gonna argue with that. the timeout is global, these may be individually specified, but that's not particularly useful at the end of the day here (you'll see this pattern in other internal code though)

2023-05-25 13:54 UTC, mimir-d commented
very nice job in refactoring the signaling part

2023-05-25 14:00 UTC, mimir-d commented on SPAG.md
> +* Successful pause is communicated by returning `Paused` from the Run method. If the plugin was responsible for any targets at the time, any other return value (including `nil`) will be considered a
well, you got what i meant. thanks

2023-05-25 14:18 UTC, xaionaro commented on pkg/signaling/signaler.go
> +			panic("was never supposed to happen")
I have no idea how to terminate this misbehavior so that I'd be happy. Basically the choice is either to ignore the misbehavior, or to panic, or to return it (in the public functions), or to log it (through standard logger, or through go-belt). All of these choices are unpleasant.

Basically if we have this misbehavior then there is no obvious way what to do next to continue executing application with messing everything up.

Pushing a version with a log.

2023-05-25 14:25 UTC, xaionaro commented on pkg/signaling/signaler.go
> +func WithSignal[T Signal](ctx context.Context, signal T) (context.Context, context.CancelFunc) {
Fixed.

On a related topic:
I've just realized in Go1.20 the problem is already solved. They added [`WithCancelCause`](https://pkg.go.dev/context#WithCancelCause). Which is not equivalent to `Paused` (which does not close the context), but close enough to get rid of `signaling` in future at all.

2023-05-25 14:33 UTC, xaionaro commented on pkg/signaling/signaler.go
> +	return signaler
Fixed.

2023-05-25 21:57 UTC, mimir-d commented on pkg/signaling/signaler.go
> +func WithSignal[T Signal](ctx context.Context, signal T) (context.Context, context.CancelFunc) {
WithCancelCause would still kinda muddy the waters since that's still a cancel signal, which goes thru the Done() chan, so any selects waiting on that would then need to switch on the cause (assuming you mean that we can use the cause as a replacement for pause signal). It's cleaner to keep them separate in my view.

i also see `check if CancelFunc and SignalFunc has the same signature` which i dont really think is necessary, but it doesnt bother anyone right now so im ok with it

2023-05-25 22:00 UTC, mimir-d commented on pkg/signaling/signaler.go
> +			panic("was never supposed to happen")
what i was thinking there is to just change the signature for `IsSignaledWith` to ret `bool, error`. that's a new func, no equiv in go stdlib, and i dont see why it couldnt be fallible

2023-05-25 22:10 UTC, mimir-d commented on cmds/admin_server/job/rdb/rdb.go
> +				logger.FromCtx(ctx).Errorf("error while closing the rows reader: %w", err)
> no longer receive information about anything added to the context

but that shouldnt be an issue to begin with. There's a slight disconnect here: 1. in other impls (and other langs), when you get a logger instance you can decorate it with new fields, structurally speaking 2. because of that general assumption, that normally leads to a pattern of passing the logger object around 3. your gobelt impl uses the context for that purpose, which is why youre making this point, but this is kinda violating expectations from the larger industry in my mind; it makes it clear that the context is the repository for logging fields instead of the logger instance (what i was saying with "not materially different from xcontext"), which was the problem we were trying to address in the first place

however, because of this construct, i dont really have a good way out of it. i guess this leads to carrying around 2 different pieces because of the disconnect, like
```go
log := logger.FromCtx(ctx)
log.something()
...
ctx = beltctx.WithField(ctx, "user_id", user.ID)
log = logger.FromCtx(ctx)
// and so on
```

but definitely having `logger.FromCtx(ctx).infof()` all over the place looks unappealing

2023-05-25 22:11 UTC, mimir-d commented on cmds/admin_server/main.go
> +	flagSet.Var(&logLevel, "logLevel", "A log level, possible values: debug, info, warning, error, panic, fatal")
thanks

2023-05-25 22:13 UTC, mimir-d commented on cmds/admin_server/server/server.go
> +	ctx = logger.CtxWithLogger(ctx, r.log)
yeah, that's what i was asking, thanks

since we cannot actually encode immutability in syntax, please ensure that there's a comment on the public api documenting this expectation/behaviour

2023-05-25 22:13 UTC, mimir-d commented on pkg/api/api.go
> +		Context:  beltctx.WithField(ctx, "api_method", "stop"),
cool, thanks

2023-05-25 22:16 UTC, mimir-d commented on pkg/loggerhook/httphook.go
> +	entry.Fields.ForEachField(func(f *field.Field) bool {
> who wants to find by key should suffer

well, now **youre** suffering from this.

im not sure how well this callback is optimized, and it may actually result in good cache coherency if it's inlined, but keep in mind that this search is done on all log calls

2023-05-25 22:18 UTC, mimir-d commented on pkg/runner/test_runner_test.go
> +	defer beltctx.Flush(ctx)
check if the cancel was actually releasing any resources (ive a feeling it was, like stopping a gorouting or something, cant remember exactly). if that's not the case, keep the code as is now

2023-05-25 22:21 UTC, mimir-d commented
> I thought we have integration tests, which check this. No?

yeah, that's fair. we'll also see if it breaks on internal usage

2023-05-26 13:25 UTC, xaionaro commented on cmds/admin_server/job/rdb/rdb.go
> +				logger.FromCtx(ctx).Errorf("error while closing the rows reader: %w", err)
> 1. in other impls (and other langs), when you get a logger instance you can decorate it with new fields, structurally speaking

You can here as well. Just those fields will go only to a specific Logger clone and will die with it (because Logger-s and contexts are immutable in this design; so if you get a logger a modify it, you get a modified clone).

> 2. because of that general assumption, that normally leads to a pattern of passing the logger object around
> 3. your gobelt impl uses the context for that purpose, which is why youre making this point, but this is kinda violating expectations from the larger industry in my mind

1. [non-important nitpick] Just to be precise: go-belt does not require to use context, it just allows to use this approach if somebody does not want to pass extra arguments around (and damage the API all across the application), but one may always fallback to old ways with passing additional variables (`Belt` or each tool separately) around, or even to fallback to a singleton approach. I just think that the contexty approach fits the best to contest.
2. [important]  The loggers used in the industry (like logrus, zap) also go with the "immutable => modified clone" approach, and they pass various clones around (instead of some global modifiable logger), branch them more and more. If you decorate a logrus logger with fields, you also get a clone of the original logger. And if you the decorate the original logger, it won't affect the clone. Here we have the exactly same thing with `go-belt`.

In other words, one can derive a `Logger` from the current context and pass it around if one wants:
```go
log = logger.FromCtx(ctx)
...
log = log.WithField("user_id", userID)
...
log.Debug("blah!")
...
someOtherFunc(ctx, log)
```
This (except for the first line) will be exactly as the logrus/zap/apexlog/whatever experience (if within `someOtherFunc` execution tree one passes the `Logger` everywhere instead of extracting it from the context). I do not like this approach because of inconsistency: we either should pass additional arguments or we should not, across the whole code. So if we decide to use `ctx` as the way to pass optional observability data then better to stick to this approach and use `ctx` as the single source of truth (instead of keeping derived `Logger`-s).

> it makes it clear that the context is the repository for logging fields instead of the logger instance (what i was saying with "not materially different from xcontext"), which was the problem we were trying to address in the first place

`go-belt` is about dependency injection. And you can always downgrade yourself to using a singleton logger which only extracts fields from the context (and I can make a PR which does that if it is useful for contest), but the problem is that you would **still** need to touch the context (get the updated fields) even with that approach, so syntaxically it won't differ from this approach (because you do not have implicit context in Go):
```go
logger.FromCtx(ctx).Errorf("blah!")
```

> but definitely having `logger.FromCtx(ctx).infof()` all over the place looks unappealing

Could you elaborate "why?"? Right now I have only two hypothesis:
1. Either it is too long/syntaxically-unaesthetic. I can try to think of some syntax sugar if that's the problem.
2. Because it has dependency on the `ctx`. But this is a necessity no matter what if we use `ctx` as the source of truth for the logged fields, because Go has no implicit contexts (it is always an explicit dependency).

2023-05-26 13:48 UTC, xaionaro commented on pkg/loggerhook/httphook.go
> +	entry.Fields.ForEachField(func(f *field.Field) bool {
> im not sure how well this callback is optimized, and it may actually result in good cache coherency if it's inlined,

[non-important] I've made some experiments:
1. Playing with reverse polish notation I tried different approaches, and apparently these callbacks was faster than having a tree of operators: https://github.com/xaionaro-go/rpn : 
```
enchmarkExpr_Eval/cache_false/10000_variables/compile-4                   84819             70461 ns/op               0 B/op          0 allocs/op
BenchmarkExpr_Eval/cache_false/10000_variables/tokenslice-4                68793             86768 ns/op               0 B/op          0 allocs/op
BenchmarkExpr_Eval/cache_false/10000_variables/default-4                  104406             57272 ns/op               0 B/op          0 allocs/op
BenchmarkExpr_Eval/cache_false/10000_variables/callslice-4                104284             57153 ns/op               0 B/op          0 allocs/op
BenchmarkExpr_Eval/cache_false/10000_variables/calltree-4                  77030             77918 ns/op               0 B/op          0 allocs/op
BenchmarkExpr_Eval/cache_false/10000_variables/exprtree-4                  60081             99462 ns/op               0 B/op          0 allocs/op
```
(`exprtree` vs `callslice`/`calltree`)

2. In `go-belt` specifically I also played with different approaches, and using these callbacks was the fastest one. Right now `go-belt` is the fastest solution I know on GitHub to handle structured fields in derived loggers.

> but keep in mind that this search is done on all log calls

1. [non-important] This linear computation is actually inavoidable at all. You can prepare a data structure which allows a faster search, but you would waste this linear computational time during preparing the data structure. `go-belt` is prefers lazy computations, so we do not do this linear computation (and memory allocation for the data structure) until its needed. So, basically, this is a drawback of the fact `go-belt` is `O(1)` (instead of being `O(n)` as the most of other loggers) on `WithField`. But still `go-belt` allows to get a data structure for a lot of quick searches if needed, we do not use it here, because here we do a single linear search.
3. [important] This linear search is way beyond negligible relatively to network IO load and even relatively to internal logrus (which is still used as the log emitter in contest) slowness. This is about like 50ns relatively to like 10000ns-100000ns (if we take network IO and other stuff into account) per log entry.

2023-05-26 14:02 UTC, xaionaro commented on pkg/signaling/signaler.go
> +func WithSignal[T Signal](ctx context.Context, signal T) (context.Context, context.CancelFunc) {
> which i dont really think is necessary, but it doesnt bother anyone right now so im ok with it

Yeaaah. I cannot explain this. Just feels like this functions is so close that if for any reason `CancelFunc` is changed (which would never happen, most likely) then this change would also be useful for `SignalFunc` as well :)

I can remove this...

2023-05-26 14:59 UTC, mimir-d commented on cmds/admin_server/job/rdb/rdb.go
> +				logger.FromCtx(ctx).Errorf("error while closing the rows reader: %w", err)
i agree with all of your points, and even prior to actually reading them because i had already thought about all that. My concern is around the `ctx` as a repository for logger fields, though as i said i dont really have a good way out of it. The other "standard" alternative is to pass the logger around, which is semantically equivalent to passing the ctx around.

For your question, im on point 1. It's a stylistic thing that bothers me (performance penalty of one indirection thru ctx can be ignored); i dont think there's a way to make that look nicer in go though, anything else would still imply a function call, and this is already at a minimum.

I'm ok with keeping the code as is. May be refactored later when better options appear.

2023-05-26 16:32 UTC, xaionaro commented on cmds/admin_server/job/rdb/rdb.go
> +				logger.FromCtx(ctx).Errorf("error while closing the rows reader: %w", err)
> It's a stylistic thing that bothers me (performance penalty of one indirection thru ctx can be ignored); i dont think there's a way to make that look nicer in go though, anything else would still imply a function call, and this is already at a minimum.

It is possible to reduce the syntax to:
```go
import . "github.com/linuxboot/contest/pkg/logging" //lint:ignore ST1001 dot-import of a Logger sugar is not a problem

    ...
    Debugf(ctx, "consistency model check: %v", value)
```
Linter's "should not use dot imports (ST1001) [go-staticcheck]" is annoying here, though.

2023-05-26 16:58 UTC, mimir-d commented on cmds/admin_server/job/rdb/rdb.go
> +				logger.FromCtx(ctx).Errorf("error while closing the rows reader: %w", err)
per discussion, something like `logging.Debugf(ctx, "format", args)` seems like an ok compromise; this is the 2nd version without the dot import

2023-05-29 15:33 UTC, xaionaro commented on cmds/admin_server/job/rdb/rdb.go
> +				logger.FromCtx(ctx).Errorf("error while closing the rows reader: %w", err)
Done.

2023-05-29 15:40 UTC, xaionaro commented on pkg/runner/test_runner_test.go
> +	defer beltctx.Flush(ctx)
It looks like all these tests run `runWithTimeout`, which has `defer cancel()` inside.

2023-05-29 15:47 UTC, xaionaro commented on pkg/signaling/signaler.go
> +			panic("was never supposed to happen")
Just for the record: in general I do not like to force the higher function always process the error returned by a lower function function if the error supposed to be mathematically impossible. But I actually do not care that much about the signature of this specific function, so OK :)

2023-05-29 16:01 UTC, xaionaro commented
Pushed a new version of the PR. Overall:

1. "Add a package to handle Pause signal" updated the `IsSignaledWith` signature.
2. "Provide shorthands for go-belt Logger" -- a new commit, requires review from scratch.
3. "Migrate from xcontext to go-belt and signaller" uses the simplified syntax for the logger, rebased to new `develop` and adapted to new `IsSignaledWith` function signature.
4. "Delete xcontext" has basically no change (just rebasing / conflict solving)
5. "Add verbosity to diagnose mis-signaling" now uses the simplified syntax for the logger.

2023-05-29 20:10 UTC, mimir-d commented
thanks for addressing all of the review items; merging

2023-05-29 20:10 UTC, mimir-d approved these changes

2023-05-29 20:10 UTC, merged