fix(api): Propagate context values
linuxboot/contest pull request #166
Opened 2023-06-16 13:30 UTC by xaionaro

See the unit-test.

2023-06-16 14:00 UTC, mimir-d requested changes
some broken code and questions

2023-06-16 14:00 UTC, mimir-d commented on pkg/api/reset_context_keep_values.go
> +	return
is there something missing here?

2023-06-16 14:00 UTC, mimir-d commented on pkg/api/reset_context_keep_values.go
> +type ctxValuesOnly struct {
would call this some sort of proxy for values

2023-06-16 14:00 UTC, mimir-d commented on pkg/api/api.go
> +	ctx, _ = signaling.WithSignal(ctx, signals.Paused) // ignore the pause signal
not sure i follow this; why is the func() ignored? means, this could never be paused, but if not, it makes this whole line not needed

2023-06-16 14:31 UTC, xaionaro commented on pkg/api/reset_context_keep_values.go
> +	return
No. This is a context, which does not receive deadline signals from the parent.

2023-06-16 14:32 UTC, xaionaro commented on pkg/api/api.go
> +	ctx, _ = signaling.WithSignal(ctx, signals.Paused) // ignore the pause signal
If the parent context has a `Pause` signal and we want to ignore it, we do it this way: we overwrite the Pause signaler and ignore its signaling function.

2023-06-16 15:22 UTC, xaionaro commented on pkg/api/reset_context_keep_values.go
> +type ctxValuesOnly struct {
Renamed.

2023-06-20 22:04 UTC, mimir-d commented on pkg/api/reset_context_keep_values.go
> +	return
it's inconsistent with other funcs in the file though

2023-06-20 22:04 UTC, mimir-d submitted a review, later dismissed

2023-06-21 07:52 UTC, marcoguerri commented on pkg/api/api.go
>  	// we care about here.
This is not correct anymore, right?

2023-06-21 13:10 UTC, xaionaro commented on pkg/api/api.go
>  	// we care about here.
Fixed.

2023-06-21 13:11 UTC, xaionaro commented on pkg/api/reset_context_keep_values.go
> +	return
Changed. But IMHO now it looks uglier (with this `time.Time{}`).

2023-06-21 13:17 UTC, mimir-d approved these changes

2023-06-21 13:32 UTC, merged