Step retries initial iteration
linuxboot/contest pull request #33
Opened 2021-11-05 19:59 UTC by rihter007

Mainly Deomid's changes in test runner + some bug fix and unit tests.
Added retry to emitted events and keep only target events with the latest retry (otherwise all reporters should be aware of retries).

TODO next:
Temporary disabled one unit test that helps to find incorrectly implemented test steps that do not reply to specific output channel as fixing it requires extra rework of Test Runner.
Also found race condition in runMonitor: we can possibly hang if test will switch to the next step before runMonitor detects. (will fix in the next PR)
Support Retry field in the database (as it requires to change database (add new column)). Will make a separate review.

This review should be safe to land.

2021-11-05 20:41 UTC, rihter007 commented
@tfg13 @insomniacslk 
I was also thinking of changing step plugin interface. Currently it consumes input/output target channels, internally launches goroutine for each target and sends result to an output channel.
Maybe we should change it to smth like: "func Run(ctx, inputTarget, emitter) (targetResult, error)" and launch goroutines for each target in test runner? IMHO it will put channels/goroutines complexity into a single place (yep, currently we have a helper for clients, but they still have flexibility to make mistakes)

2021-11-06 19:45 UTC, rihter007 commented on pkg/event/testevent/test.go
> +	TestStepRetry int
We need to filter target statuses by last retry (otherwise we should put this logic to all reporters).
There are two ways:
- explicitly add retry (as currently done here)
- sort events by EmitTime and use windows based on "known" start/finish/error events.
I decided to go with the first one, as it is more explicit. But it requires more changes

2021-11-08 17:19 UTC, tfg13 commented
> @tfg13 @insomniacslk I was also thinking of changing step plugin interface. Currently it consumes input/output target channels, internally launches goroutine for each target and sends result to an output channel. 
Not all plugins do this. We have some that gather all the targets (until input channel closed) and then run one bulk job with them. Would that still work then?

But yeah you are right, writing plugins is too complicated.

2021-11-11 11:59 UTC, rihter007 commented
> > @tfg13 @insomniacslk I was also thinking of changing step plugin interface. Currently it consumes input/output target channels, internally launches goroutine for each target and sends result to an output channel. 
> 
> Not all plugins do this. We have some that gather all the targets (until input channel closed) and then run one bulk job with them. Would that still work then?
> 
> 
> 
> But yeah you are right, writing plugins is too complicated.
> 
> 
> 
> 
> 
> 
> 
> 

Thanks, I will make the proposal in a different PR

2021-11-14 14:33 UTC, rihter007 commented
Please start reviewing with PR 37, as it has the same concept, but contains less changes

2021-11-15 23:37 UTC, mimir-d commented
> > > @tfg13 @insomniacslk I was also thinking of changing step plugin interface. Currently it consumes input/output target channels, internally launches goroutine for each target and sends result to an output channel.
> > 
> > 
> > Not all plugins do this. We have some that gather all the targets (until input channel closed) and then run one bulk job with them. Would that still work then?
> > But yeah you are right, writing plugins is too complicated.
> 
> Thanks, I will make the proposal in a different PR

I'm also interested to find out why this "system pipeline" mechanism was written for test steps. As in, a single goro is created and receives targets in a channel. Might be some sequencing thing that escapes me at the moment.

2021-11-16 01:03 UTC, mimir-d commented on pkg/runner/test_runner.go
> +			if tgs.CurRetry > ss.sb.RetryParameters.NumRetries {
nit; this seems more like a MaxRetries, rather than NumRetries

2021-11-16 01:04 UTC, mimir-d commented
a number of my comments on #37 also apply here; stuff related to retries

2021-11-21 18:46 UTC, rihter007 commented
Will have to rework the PR.
It also requires some prior work of moving step running logic into a separate entity

2021-11-23 02:01 UTC, mimir-d requested changes
just returning back to author queue

2021-11-26 22:11 UTC, rihter007 commented
Waiting for: https://github.com/linuxboot/contest/pull/48

2021-12-17 13:11 UTC, rihter007 commented
I will rework everything and start a new PR.

2021-12-17 13:11 UTC, closed without merging