Move storage engines from global vars into the vault
linuxboot/contest pull request #36
Opened 2021-11-10 14:10 UTC by max2k1

2021-11-21 18:32 UTC, rihter007 commented on pkg/storage/vault.go
> +type EngineType string
Let's do it as uint32 instead of a string?

2021-11-21 18:45 UTC, rihter007 requested changes
Thanks for handling this!
I left some minor comments. 
The PR requires rebasing followed by re-stamping anyway

2021-11-21 18:45 UTC, rihter007 commented on pkg/storage/vault.go
> +	DefaultEngine EngineType = "DefaultEngine"
I would use Sync instead of default.
Actually, both of them represent the same database, but one always communicate to a primary, another to secondary db node.

2021-11-21 18:45 UTC, rihter007 commented on pkg/storage/vault.go
> +func (v *SynchronizedEngineVault) GetEngine(engineType EngineType) (res Storage, err error) {
nit: I would leave (Storage, err (without variable names).
In this case the purpose of return arguments is clear

2021-11-21 18:45 UTC, rihter007 commented on pkg/storage/vault.go
> +type SynchronizedEngineVault struct {
The storage is initialised once in the beginning, so we can get rid of synchronisation by leaving just "reader" part of the interface with GetEngine() only.

2021-11-21 18:45 UTC, rihter007 commented on pkg/storage/vault_test.go
> +	"testing"
nit

let import be like:

import (
   "testing"

  "github.com/stretchr/testify/require"
)

2021-11-23 01:59 UTC, mimir-d requested changes
Thanks Max. As far as I'm concerned this branch correctly addresses all of the issues. I'm just returning this to your queue for the panic() calls. The other nits may or may not be resolved.

2021-11-23 01:59 UTC, mimir-d commented on cmds/contest/server/server.go
> +	vault.Clear()
nit; this correctly refactors existing code, but it doesnt look like it's necessary though because the state is no longer global (if this is the only usage of .Clear, the method might not be necessary itself)

2021-11-23 01:59 UTC, mimir-d commented on pkg/storage/events.go
> +		panic("engine storage is not set")
this should just return an error here instead of panic; the contest server is used in some sensitive environment and crashing the whole process is not desirable

2021-11-23 01:59 UTC, mimir-d commented on pkg/storage/events.go
> +		panic("engine storage is not set")
same comment here as on line :51

2021-11-23 01:59 UTC, mimir-d commented on pkg/storage/events.go
> +		panic("engine storage is not set")
same comment here as on line :51

2021-11-23 01:59 UTC, mimir-d commented on pkg/storage/events.go
> +		panic("engine storage is not set")
same comment here as on line :51

2021-11-23 01:59 UTC, mimir-d commented on plugins/storage/memory/memory.go
> +	// Copyright (c) Facebook, Inc. and its affiliates.
nit; some empty space here by mistake

2021-11-23 01:59 UTC, mimir-d commented on tests/integ/jobmanager/common.go
> +	suite.storageEngineVault.Clear()
nit; this is probably not needed anymore because SetupTest initializes new stuff instead of setting global state

2021-11-23 18:08 UTC, rihter007 commented
@max2k1 could you please do the

git checkout main
git pull
git checkout EliminateStorageVars
git push --force
?

Otherwise the PR contains too many changes that were not originally introduced in this PR :)

2021-11-23 18:52 UTC, mimir-d commented
> 

yeah, there's a discussion on that pending offline

2021-11-23 18:58 UTC, mimir-d approved these changes

2021-11-23 19:02 UTC, mimir-d commented
@rihter007 im gonna do a squash commit this time as was requested offline (and I'll fix anything that breaks). This would result in fixing all of the duplicated commits from committer branch and upstream, but it will make history opaque for this feature. (reverting your request for changes in order to merge)

2021-11-23 19:04 UTC, mimir-d commented
@rihter007 hm.. I'm not sure if reverting the review will also deleted the comments. So I'll wait for you to accept it.

2021-11-23 22:41 UTC, rihter007 commented on pkg/storage/vault.go
> +		err = fmt.Errorf("storage #{engineType} not assigned")
Didn't know that "storage #{engineType} not assigned" will put variable value, nice!

2021-11-23 22:42 UTC, rihter007 approved these changes
LGTM, thanks!

2021-11-24 02:01 UTC, merged