Refactor implement step runner
linuxboot/contest pull request #48
Opened 2021-11-25 16:28 UTC by rihter007

Move all logic that manages running of a TestStep in a separate TestRunner.
This refactoring is needed to make retries of steps look better.

Special thanks to @rojer for a large number of unit tests :)

2021-11-25 16:32 UTC, rihter007 commented
StepRunner logic is covered by TestRunner unit tests.
If this approach gets approved, I will add some unit tests for StepRunner as well

2021-11-25 23:51 UTC, rihter007 commented
Cool, tests found existing race-condition, in case of an error, we may not "switch" to result processing branch in waitStepRunners method

time="2021-11-25T23:30:03Z" level=debug msg="monitor: active" file="test_runner.go:611"
time="2021-11-25T23:30:03Z" level=debug msg="monitor: starting at step [#0 Step 1]" file="test_runner.go:616"
time="2021-11-25T23:30:03Z" level=debug msg="[Target{ID: \"T1\"} 0 init false <nil>]: target handler active" file="test_runner.go:424" target=T1
time="2021-11-25T23:30:03Z" level=debug msg="monitor pass 1: current step [#0 Step 1]" file="test_runner.go:625"
time="2021-11-25T23:30:03Z" level=debug msg="monitor pass 1: [#0 Step 1]: [Target{ID: \"T1\"} 0 init false <nil>]" file="test_runner.go:629"
time="2021-11-25T23:30:03Z" level=debug msg="monitor pass 1: [#0 Step 1]: not all targets injected yet ([Target{ID: \"T1\"} 0 init false <nil>])" file="test_runner.go:634"
time="2021-11-25T23:30:03Z" level=debug msg="[Target{ID: \"T1\"} 0 begin false <nil>]: injecting into [#0 Step 1]" file="test_runner.go:350" target=T1
time="2021-11-25T23:30:03Z" level=debug msg="monitor pass 2: current step [#0 Step 1]" file="test_runner.go:625"
time="2021-11-25T23:30:03Z" level=debug msg="monitor pass 2: [#0 Step 1]: [Target{ID: \"T1\"} 0 run false <nil>]" file="test_runner.go:629"
time="2021-11-25T23:30:03Z" level=info msg="Obtained '{Target{ID: \"T1\"} <nil>}' for target 'T1'" file="step_runner.go:178" step_index=0 step_label="Step 1"
time="2021-11-25T23:30:03Z" level=debug msg="monitor pass 2: [#0 Step 1]: no more targets, closing input channel" file="test_runner.go:648"
time="2021-11-25T23:30:03Z" level=debug msg="Input channel was closed" file="step_runner.go:145" step_index=0 step_label="Step 1"
time="2021-11-25T23:30:03Z" level=debug msg="TestStep finished '<nil>', rs " file="step_runner.go:230" step_index=0 step_label="Step 1"
time="2021-11-25T23:30:03Z" level=debug msg="monitor: waiting for targets to finish" file="test_runner.go:653"
time="2021-11-25T23:30:03Z" level=debug msg="monitor pass 3: [Target{ID: \"T1\"} 0 run false <nil>]" file="test_runner.go:661"
time="2021-11-25T23:30:03Z" level=error msg="err: test step Step 1 closed output channels (api violation)" file="step_runner.go:249" step_index=0 step_label="Step 1"
time="2021-11-25T23:30:03Z" level=debug msg="output channel closed" file="step_runner.go:210" step_index=0 step_label="Step 1"
time="2021-11-25T23:30:03Z" level=debug msg="Running loop finished" file="step_runner.go:96" step_index=0 step_label="Step 1"
time="2021-11-25T23:30:03Z" level=debug msg="[#0 Step 1]: result for [Target{ID: \"T1\"} 0 result_pending false <nil>]: <nil>" file="test_runner.go:569" step_index=0 step_label="Step 1"
time="2021-11-25T23:30:03Z" level=error msg="err: test step Step 1 closed output channels (api violation)" file="test_runner.go:515" step_index=0 step_label="Step 1"
time="2021-11-25T23:30:03Z" level=debug msg="monitor: finished, test step Step 1 closed output channels (api violation)" file="test_runner.go:689"
time="2021-11-25T23:30:03Z" level=error msg="monitor returned error: \"test step Step 1 closed output channels (api violation)\", canceling" file="test_runner.go:216"
time="2021-11-25T23:30:03Z" level=debug msg="waiting for step runners to finish" file="test_runner.go:306"
time="2021-11-25T23:30:03Z" level=debug msg="waiting for target handlers to finish" file="test_runner.go:228"
time="2021-11-25T23:30:03Z" level=debug msg="[Target{ID: \"T1\"} 0 result_pending false <nil>]: canceled 2" file="test_runner.go:414" target=T1
time="2021-11-25T23:30:03Z" level=error msg="context canceled" file="test_runner.go:475" step_index=0 step_label="Step 1"
time="2021-11-25T23:30:03Z" level=debug msg="[Target{ID: \"T1\"} 0 result_pending false <nil>]: canceled 1" file="test_runner.go:480" step_index=0 step_label="Step 1"
time="2021-11-25T23:30:03Z" level=debug msg="[Target{ID: \"T1\"} 0 result_pending false <nil>]: target handler finished" file="test_runner.go:499" target=T1
time="2021-11-25T23:30:03Z" level=debug msg="leaving, err test step Step 1 closed output channels (api violation), target states:" file="test_runner.go:240"
time="2021-11-25T23:30:03Z" level=debug msg="  0 [Target{ID: \"T1\"} 0 result_pending true <nil>] test step Step 1 closed output channels (api violation) false" file="test_runner.go:257"
time="2021-11-25T23:30:03Z" level=debug msg="- 0 in flight, ok to resume? false" file="test_runner.go:259"
time="2021-11-25T23:30:03Z" level=debug msg="Output channel closed" file="step_runner.go:163" step_index=0 step_label="Step 1"
time="2021-11-25T23:30:03Z" level=debug msg="step states:" file="test_runner.go:260"
time="2021-11-25T23:30:03Z" level=debug msg="Reading loop finished" file="step_runner.go:102" step_index=0 step_label="Step 1"
time="2021-11-25T23:30:03Z" level=debug msg="StepRunner finished" file="step_runner.go:89" step_index=0 step_label="Step 1"
time="2021-11-25T23:30:03Z" level=debug msg="  0 [#0 Step 1] true true test step Step 1 closed output channels (api violation) " file="test_runner.go:262"
--- FAIL: TestTestRunnerSuite (2.23s)
    --- FAIL: TestTestRunnerSuite/TestStepClosesChannels (0.01s)
        test_runner_test.go:381: 
            	Error Trace:	test_runner_test.go:381
            	Error:      	Not equal: 
            	            	expected: "\n{[1 1 SimpleTest 0 Step 1][Target{ID: \"T1\"} TargetIn]}\n{[1 1 SimpleTest 0 Step 1][Target{ID: \"T1\"} TargetOut]}\n"
            	            	actual  : "\n{[1 1 SimpleTest 0 Step 1][Target{ID: \"T1\"} TargetIn]}\n"
            	            	
            	            	Diff:
            	            	--- Expected
            	            	+++ Actual
            	            	@@ -2,3 +2,2 @@
            	            	 {[1 1 SimpleTest 0 Step 1][Target{ID: "T1"} TargetIn]}
            	            	-{[1 1 SimpleTest 0 Step 1][Target{ID: "T1"} TargetOut]}
            	            	 
            	Test:       	TestTestRunnerSuite/TestStepClosesChannels
FAIL
FAIL	github.com/linuxboot/contest/pkg/runner	7.078s
FAIL
1

Another test fails because it lasted 7 seconds instead of 5... The test checks exec plugin that launches actual ssh stuff. Will extend timeout.

2021-11-26 00:18 UTC, rojer commented
> Special thanks to @rojer for a large number of unit tests :)

you are welcome :)
i really tried to test it well after rewrite. of course, i did miss one case so it ended up blowing up anyway on first attempt...
but hopefully these tests will now help you.

2021-11-30 02:47 UTC, mimir-d requested changes

2021-11-30 02:47 UTC, mimir-d commented on pkg/runner/test_runner.go
> +		if err == context.DeadlineExceeded {
this error check is kinda fragile. it would be more semantically correct to write it as a race to result, since what youre checking for is that shutdownCtx expired; like
```
waited := make(chan struct, 1)
go func() { waited <- WaitResults(...) }
select {
   case r <- waited:
       // check returned error (and log it probably, currently if err is anything different than DeadlineExceeded it's just dropped)
   case <-shutdownCtx.Done():
       neverReturned = append(...)
       ss.cancel()
}
```

2021-11-30 02:47 UTC, mimir-d commented on pkg/runner/test_runner.go
>  	tr.cond.Signal()
nit; this cond var is really obscure; could use this occasion to rename it because it's not clear what it's signalling here (or add some comment)

2021-11-30 02:47 UTC, mimir-d commented on pkg/runner/test_runner.go
> +		func() {
nit; too much verbosity for a defer unlock; considering there are other cases in this same code that just do lock; action; unlock

2021-11-30 02:47 UTC, mimir-d commented on pkg/runner/test_runner.go
> +			if tgs.CurPhase == targetStepPhaseBegin {
what's the data of `tr` that's actually protected by the `tr.mu` lock? i just see the `tgs` that looks unrelated

2021-11-30 02:47 UTC, mimir-d commented on pkg/runner/test_runner.go
> +	processResult := func(res error) error {
nit; this really looks like a TestRunner method; similar to awaitTargetResult, you can have processTargetResult

2021-11-30 02:47 UTC, mimir-d commented on pkg/runner/test_runner.go
> +		// in this case we should prioritise result processing
nit; i dont quite follow this comment, where is the prioritization happening?

2021-11-30 02:47 UTC, mimir-d commented on pkg/runner/test_runner.go
> +	// As it has buffer size 1 and we process a single result for each target at a time
nit; in this function, the fact that resCh has a buffer of 1 is an implementation detail and therefore unknown

2021-11-30 02:47 UTC, mimir-d commented on pkg/runner/test_runner.go
>  	resCh, err := func() (chan error, error) {
could you refactor out this immediately called function? it doesnt seem to provide any value in tr.reportTargetResult as it's essentially the same body

2021-11-30 02:47 UTC, mimir-d commented on tests/integ/plugins/testrunner_test.go
> +	successTimeout = 20 * time.Second
nit; does this fail often enough to warrant the 4x increase? we'd like to minimize the run time of the tests

2021-11-30 02:47 UTC, mimir-d commented on pkg/runner/step_runner.go
> +	if !atomic.CompareAndSwapUint32(&sr.started, 0, 1) {
nit; you have a compare & exchange here but in stop you use a sync.Once. you could use a sync.Once here as well and make Run reentrant; a step runner is only run once per test runner so it makes sense

2021-11-30 02:47 UTC, mimir-d commented on pkg/runner/step_runner.go
> +	var activeLoopsCount int32 = 2
nit; there's sync.WaitGroup for this

2021-11-30 02:47 UTC, mimir-d commented on pkg/runner/step_runner.go
> +	onFinished := func() {
nit; event type naming; suggestion would be imperative for funcs, like `finish`

2021-11-30 02:47 UTC, mimir-d commented on pkg/runner/step_runner.go
> +	stepFinished := sr.finishedCh
nit; why not keep  the same name? `finishedCh`

2021-11-30 02:47 UTC, mimir-d commented on pkg/runner/step_runner.go
> +		if r := recover(); r != nil {
q; is there really a usecase for this? why would this panic? in any case, you can avoid it completely by using the idiomatic chans for events

2021-11-30 02:47 UTC, mimir-d commented on pkg/runner/step_runner.go
> +	return atomic.LoadUint32(&sr.started) == 1
nit; you use `sr.mu` in most of the code; why have this atomic?

2021-11-30 02:47 UTC, mimir-d commented on pkg/runner/step_runner.go
> +			recoverOccurred = true
this construct is very.. unnatural. if closing your chan panics, then it's a sign of requires refactoring; my opinion is to either keep track of the channel or refactor such that the knowledge is implicit (preferred)

2021-11-30 02:47 UTC, mimir-d commented on pkg/runner/step_runner.go
> +		if r := recover(); r != nil {
nit; since this may actually happen with externally written test step plugins, id rather make an explicit case out of it and just have this defer/recover and the TestStep.Run in a single method

2021-11-30 23:54 UTC, rihter007 commented on pkg/runner/test_runner.go
> +		ss.resumeState = resumeState
True, but it is the "initial" design.
Everything is synchronised with TestRunner's lock.
I guess this could be because the lock contention is small and having this in mind having less locks == having less code :)

2021-11-30 23:54 UTC, rihter007 commented on pkg/runner/test_runner.go
> +		if err == context.DeadlineExceeded {
this creates a problem to wait all this goroutines...

2021-12-05 18:37 UTC, rihter007 commented on pkg/runner/test_runner.go
>  			ctx:         stepCtx,
It is not as easy as it sounds :)

2021-12-05 18:40 UTC, rihter007 commented on pkg/runner/step_runner.go
> +	if !atomic.CompareAndSwapUint32(&sr.started, 0, 1) {
This is because one can pass different parameters in Run during the second call.
I made StepRunner look like TestRunner, but I do not like this concept

2021-12-05 19:38 UTC, rihter007 commented on pkg/runner/test_runner.go
>  			ctx:         stepCtx,
Hm, I need to keep ctx in StepRunner to share it between multiple functions calls. (To be able to break waiting AddTarget on internal "smth" if StepRunner stop, so I need to share smth anyway it will be either context or channel).

I reduced the number of step state context usages in this PR

2021-12-05 19:43 UTC, rihter007 commented on pkg/runner/step_runner.go
> +		panic("target callback should not be nil")
I agree, though it is a very straightforward violation that we would catch in unit tests.
Ok, let it be an error :)

2021-12-05 19:44 UTC, rihter007 commented on pkg/runner/step_runner.go
> +	targetCallback OnTargetResult,
Yep, we can avoid recovering as we can assume that "core" code is tested well enough.
I'm still not sure about channels vs callbacks, we think more

2021-12-05 19:59 UTC, rihter007 commented on pkg/runner/test_runner.go
> +		ss.resumeState = resumeState
step state (ss) doesn't contain locks. We do not have a lot of lock contention, so it is ok.
This behaviour of using TestRunner's lock for all step state is obtained from previous implementation.
I think it needs a separate refactoring PR

2021-12-05 20:04 UTC, rihter007 commented on pkg/runner/test_runner.go
>  	for _, ss := range tr.steps {
This lock protects ss.Err :)
I inherited it from the previous code, let me try to make it a bit more clear!

2021-12-05 20:25 UTC, rihter007 commented on pkg/runner/test_runner.go
> +		if err == context.DeadlineExceeded {
It is fragile is there is a bug in WaitResults() that doesn't wait on input context properly.
If there is a bug in WaitResults, let's better fix it.

2021-12-05 20:29 UTC, rihter007 commented on pkg/runner/test_runner.go
> +			if tgs.CurPhase == targetStepPhaseBegin {
tr.mu is a global lock, it protects everything...
As noted above, it is an inherited behaviour. Let's keep it as is in the current PR.

2021-12-05 20:39 UTC, rihter007 commented on pkg/runner/test_runner.go
> +		// in this case we should prioritise result processing
It could be the case when both <-ctx.Done() and <-resCh is ready when awaitTargetResult is called.

2021-12-05 20:48 UTC, rihter007 commented on pkg/runner/test_runner.go
> +	// As it has buffer size 1 and we process a single result for each target at a time
But everything happens within the same TestRunner entity...

2021-12-05 20:49 UTC, rihter007 commented on pkg/runner/test_runner.go
>  	resCh, err := func() (chan error, error) {
I believe this is because the internal functions provides a scope for holding the lock

2021-12-05 20:51 UTC, rihter007 commented on tests/integ/plugins/testrunner_test.go
> +	successTimeout = 20 * time.Second
No, it doesn't fail often.
The test time will increase only in case of a "failure", so I believe it is ok as it is  "longer" vs "failed" (which will require re-run)

2021-12-05 20:53 UTC, rihter007 commented on pkg/runner/step_runner.go
> +	var activeLoopsCount int32 = 2
Yes, they are similar. But WaitGroup will end up having a bit less straightforward code.

2021-12-05 20:55 UTC, rihter007 commented on pkg/runner/step_runner.go
> +		if r := recover(); r != nil {
Addressed above, agree that we do not need that recovery wrapping if the code doesn't go into plugins

2021-12-05 20:56 UTC, rihter007 commented on pkg/runner/step_runner.go
> +	return atomic.LoadUint32(&sr.started) == 1
To put less lines of code :)

2021-12-05 20:59 UTC, rihter007 commented on pkg/runner/step_runner.go
> +			recoverOccurred = true
This is done because the chan is consumed by a plugin which could be written badly.
In order for a single plugin not to ruin the whole test data, we do such a trick.

(This behaviour was implemented initially, I just moved it and I think this is the reason)

2021-12-05 21:00 UTC, rihter007 commented on pkg/runner/step_runner.go
> +		if r := recover(); r != nil {
Will make an inline

2021-12-06 00:10 UTC, rihter007 commented on pkg/runner/step_runner.go
> +	targetCallback OnTargetResult,
I tried to use channels, I got more lines of code + need to launch two goroutines (for stop and events).
While without them, the code is more compact.

I guess it is not a big change, so if we need later to use channels, we can easily switch to them.

2021-12-06 08:58 UTC, tfg13 commented on pkg/runner/step_runner.go
> +			recoverOccurred = true
yes, that was the idea, we want to be as stable as possible with buggy plugins (and fail the job in a graceful way)

2021-12-06 08:58 UTC, tfg13 commented on pkg/cerrors/cerrors.go
> +type ErrAlreadyDone struct {
please put a quick comment that describes what this error means (like the others have :) )

2021-12-09 02:14 UTC, mimir-d commented on pkg/runner/test_runner.go
> +		ss.resumeState = resumeState
ok, please post an issue on this and link it here

2021-12-09 02:20 UTC, mimir-d commented on pkg/runner/test_runner.go
> +		if err == context.DeadlineExceeded {
not sure i understand your answer. it is incorrect to expect WaitResults (or whatever other function) to return an explicit DeadlineExceeded error and make decision based on it, the decision should be in the caller (who controls the logic here since it contains the decision), but anyway ignoring that implementation leak, it would at least be better to use errors.Is since it covers other cases where the error can be presented in a different shape (although this can still fail because of the tight coupling)

2021-12-09 02:22 UTC, mimir-d commented on pkg/runner/test_runner.go
> +			if tgs.CurPhase == targetStepPhaseBegin {
im ok with that if it's captured in another Issue/PR

2021-12-09 02:24 UTC, mimir-d commented on pkg/runner/test_runner.go
> +		// in this case we should prioritise result processing
ah ok. it's clear now, thanks

2021-12-09 02:36 UTC, mimir-d commented on pkg/runner/test_runner.go
> +	// As it has buffer size 1 and we process a single result for each target at a time
well yes, but this is still implementation leakage (in general, if you have 2 methods on the same object and data that is not owned by that object instance, you should not depend in one method on the internal state of the other)
Here it's not exactly that, but the interaction is `tr` assuming a relevant property of `tr.targets[tgt.ID].resCh` (that may cause a deadlock if violated and there is no official contract for that on the callee side).
In any case, i marked it a `nit` so i'll just close.

2021-12-09 02:39 UTC, mimir-d commented on pkg/runner/test_runner.go
>  	resCh, err := func() (chan error, error) {
yes, but it looks to me like you can have the same lock behaviour without this function call as well; the outside caller doesnt have anything else that would be sensitive to that and to me it just looks like
```
func a() {
   return func(){
      return 42
   }()
}
```

2021-12-09 02:48 UTC, mimir-d commented on pkg/runner/step_runner.go
> +	var activeLoopsCount int32 = 2
how so? example (idiomatic go):
```
var wg WaitGroup

wg.Add(1)
go func(){
  defer wg.Done()
  // running loop
}()

wg.Add(1)
go func(){
  defer wg.Wait()
  // reading loop
}()

go func(){
  wg.Wait()
  // cleanup code from finish()
}()
```

why is this less straightforward than keeping tabs on atomic operations?

2021-12-09 02:50 UTC, mimir-d commented on pkg/runner/step_runner.go
> +	return atomic.LoadUint32(&sr.started) == 1
even if that's the case, why complicate the code with an additional lock when you have an object wide one already?

2021-12-09 02:52 UTC, mimir-d commented on pkg/runner/step_runner.go
> +			recoverOccurred = true
well if the plugins are adversarial, id argue a better way around this is issue #21 ; i'll close this for now

2021-12-09 17:16 UTC, mimir-d commented on pkg/runner/step_runner.go
> +	if !atomic.CompareAndSwapUint32(&sr.started, 0, 1) {
i didnt conceptualize that this .Run can be called multiple times, but it seems it technically can, although the default will be just once. This makes little sense to me, but this should be refactored later on

2021-12-09 17:18 UTC, mimir-d commented on pkg/runner/test_runner.go
>  			ctx:         stepCtx,
if you would, please post an Issue with this in order to track it

2021-12-09 22:28 UTC, rihter007 commented on pkg/runner/test_runner.go
>  			ctx:         stepCtx,
https://github.com/linuxboot/contest/issues/53

2021-12-09 22:29 UTC, rihter007 commented on pkg/runner/step_runner.go
> +	return atomic.LoadUint32(&sr.started) == 1
Agree let's use a single synchronisation mechanism

2021-12-09 22:56 UTC, rihter007 commented on pkg/runner/test_runner.go
> +			if tgs.CurPhase == targetStepPhaseBegin {
https://github.com/linuxboot/contest/issues/52

2021-12-09 23:04 UTC, rihter007 commented on pkg/runner/test_runner.go
>  	resCh, err := func() (chan error, error) {
Oh, I see your point, I think the initial idea was not to write into channel under lock.
But because we channel should always have enough capacity (so it will not block), it should be ok to refactor it. 
(otherwise there would be some other bugs like writing to a closed channel)

2021-12-09 23:16 UTC, rihter007 commented on pkg/runner/step_runner.go
> +	var activeLoopsCount int32 = 2
Why do you think that it is more idiomatic in go? In WaitGroup examples, this synchronisation primitive is used to make explicit wait for a group of events to happen before moving forward. While here, we want to just make some "auxiliary" action that doesn't block the main flow. + Here atomics allow to even have less lines of code and do not require to create extra goroutine to just wait for results.

Both atomics and WaitGroup are synchronisation primitives each have their own scope. IMHO one should pick the one that will be more readable (+ probably be faster). IMHO in this particular case WaitGroup is an overkill.

2021-12-10 08:35 UTC, tfg13 commented on pkg/runner/step_runner.go
> +	var activeLoopsCount int32 = 2
I think at the end this comes down to what people are more used to. I am waaay more used to reading code with `WaitGroup`s. I can understand this one, but it took one more moment to wrap my head about it. The strongest argument for using WaitGroups is probably that we already use a bunch of them everywhere. We also have the atomic primitives, but not as many.

I don't know what is idiomatic golang, but the docs for the atomic package say avoid it if you can:
> These functions require great care to be used correctly. Except for special, low-level applications, synchronization is better done with channels or the facilities of the sync package.

2021-12-10 16:27 UTC, rihter007 commented on pkg/runner/step_runner.go
> +	var activeLoopsCount int32 = 2
Ok, two vs one. Will rework this part :)

2021-12-11 00:03 UTC, rihter007 commented on pkg/runner/step_runner.go
> +	targetCallback OnTargetResult,
Reworked to use channels with a single channel for both events and a single goroutine for handling.

2021-12-11 00:05 UTC, rihter007 commented on pkg/runner/step_runner.go
> +	var activeLoopsCount int32 = 2
Oh no... Another moral choice. Some tests explicitly hang in Run() that leaks this goroutine.
One can add it to exceptions, but it will not be as pretty as:

	goroutine_leak_check.LeakCheckingTestMain(m,
		// We expect these to leak.
		"github.com/linuxboot/contest/tests/plugins/teststeps/hanging.(*hanging).Run",
		"github.com/linuxboot/contest/tests/plugins/teststeps/noreturn.(*noreturnStep).Run",

2021-12-11 00:35 UTC, rihter007 commented on pkg/runner/test_runner.go
>  	resCh, err := func() (chan error, error) {
Returned behaviour... fully original behaviour, opened issue: https://github.com/linuxboot/contest/issues/54

2021-12-14 09:17 UTC, tfg13 commented on pkg/runner/step_runner.go
> +	var activeLoopsCount int32 = 2
Which goroutine do you mean, the readingLoop?
Two questions:
- How terrible is it to just add the exception? (those are tests that hang on purpose to make sure the engine can handle it)
- Why does this not break the test runs right now? It seems to me the tests are all green at the moment?

2021-12-15 00:01 UTC, rihter007 commented on pkg/runner/step_runner.go
> +	var activeLoopsCount int32 = 2
>> How terrible is it to just add the exception?
Kind of, it requires to make a

go func() {
  sr.finish(ctx, wg)
}()

fun (sr *StepRunner) finish(ctx xcontext, wg WaitGroup) {
 wg.Wait()
...
}

To add StepRunner.finish to this exception list... Which doesn't make code clear. (simple atomic decrement vs this)

>> Why does this not break the test runs right now? It seems to me the tests are all green at the moment?
Because we leak only goroutine that hangs (and it is already added to exceptions).

2021-12-15 00:49 UTC, mimir-d commented on pkg/runner/step_runner.go
> +	var activeLoopsCount int32 = 2
you currently have a finish lambda, so it's not exactly `sr.finish(ctx, wg)`. it would be similar to what i exemplified
```
go func(){
   wg.Wait()
   // finish lambda code here inline
}()
```
why do you say this more complicated than having that deferred finish lambda call that checks that it was called exactly twice with that atomic count? it's a standard golang construct, take multiple goroutines and a final one that checks that all the others are done. Normally with the wg.Wait inside main goroutine, this is different in just where the wg.Wait is placed.

2021-12-15 00:52 UTC, mimir-d commented on pkg/runner/step_runner.go
> +	var activeLoopsCount int32 = 2
> Because we leak only goroutine that hangs (and it is already added to exceptions).

I have to reiterate on the fact that the check for hung goroutines makes some invalid assumptions, and the fact that this code passes with the atomic+lambda form is a consequence of that. What is the failing test exactly?

2021-12-15 01:02 UTC, rihter007 commented on pkg/runner/step_runner.go
> +	var activeLoopsCount int32 = 2
Sorry, my clarification is probably misleading.

One can't whitelist a lambda (because lambda gets an implementation specific name)

So this code is not an option:
```
go func(){
   wg.Wait() <- the wait (and hang) will happen here
   // finish lambda code here inline
}()
```

But an option is for example this one:
```
go func(){
   sr.finish(ctx, wg)
}()

func (sr *StepRunner) finish(ctx, wg) {
    wg.Wait()
}
```
In this case I will be able to whitelist StepRunner.finish method that has a determenistic name

2021-12-15 01:06 UTC, rihter007 commented on pkg/runner/step_runner.go
> +	var activeLoopsCount int32 = 2
> I have to reiterate on the fact that the check for hung goroutines makes some invalid assumptions...

It makes an assumption:

```
	goroutine_leak_check.LeakCheckingTestMain(m,
		// We expect these to leak.
		"github.com/linuxboot/contest/tests/plugins/teststeps/hanging.(*hanging).Run",
		"github.com/linuxboot/contest/tests/plugins/teststeps/noreturn.(*noreturnStep).Run",
```

That leaked goroutines will have in their callstack (*noreturnStep).Run or (*hanging).Run which is correct.

> What is the failing test exactly?

That we have a leaked goroutine with non-whitelisted callstack:

```
go func(){
   wg.Wait() <- the wait (and hang) will happen here
   // finish lambda code here inline
}()
```
In case of 
go func(){
   sr.finish(ctx, wg)
}()

I can add

"github.com/linuxboot/contest/.../stepr_unner.go.(StepRunner).finish"

But this in total makes code more convoluted then simple `atomic.Decrement(&counter)`

2021-12-15 01:11 UTC, rihter007 commented on pkg/runner/step_runner.go
> +	var activeLoopsCount int32 = 2
If you don't prefer atomics, I can do decrement under mutex which is widely used in this class

2021-12-15 15:00 UTC, mimir-d commented on pkg/runner/step_runner.go
> +	var activeLoopsCount int32 = 2
ok, now i understand that the problem with whitelisting was that you need to have a known name for the lambda. In order to avoid dragging this for too long, i'll accept this as is and we'll discuss this again in the context of the issue related to running pluggins in their own processes (which will also make the goroutine leak test obsolete). Thanks

2021-12-15 15:00 UTC, mimir-d approved these changes

2021-12-15 16:00 UTC, merged