Improve BaseTestSuite
linuxboot/contest pull request #56
Opened 2021-12-15 19:43 UTC by rihter007

Move global variable ctx into suite
Use BaseTestSuite in TestRunner tests

2021-12-15 23:19 UTC, mimir-d requested changes

2021-12-15 23:19 UTC, mimir-d commented on pkg/runner/base_test_suite_test.go
> +	Ctx    xcontext.Context
there's very clear guidelines on not keeping contexts in structs
> Do not store Contexts inside a struct type; instead, pass a Context explicitly to each function that needs it. The Context should be the first parameter, typically named ctx: 

instead this should be created (and cancelled) on a per test basis

2021-12-16 11:53 UTC, rihter007 commented on pkg/runner/base_test_suite_test.go
> +	Ctx    xcontext.Context
I agree with this guidelines in general, but this is a TestSuite which is some sort of global environment for each test.
It is handy because:
- I use context during TestSetup() (which can't be passed from the test itself, so I will have two context in the test)
- Tests do not get simple, but yet redundant logic of context initialisation with logs support + cancelling it (I agree that it is short, but still it is code duplication).

2021-12-16 11:53 UTC, rihter007 commented on pkg/runner/base_test_suite_test.go
> +	Ctx    xcontext.Context
Ha-ha, noticed that the first point is affected by NewPluginRegistry that doesn't follow that guideline

2021-12-16 11:57 UTC, rihter007 commented on pkg/runner/base_test_suite_test.go
> +	Ctx    xcontext.Context
Indeed I can get rid of context in MemoryStorageEngine

2021-12-17 04:08 UTC, mimir-d commented on pkg/runner/base_test_suite_test.go
> +	Ctx    xcontext.Context
this usage here `s.PluginRegistry = pluginregistry.NewPluginRegistry(s.Ctx)` should not exist to begin with. What's being used there in terms of semantics is a logger, not a cancellation context. I'll accept the review as is right now, but please post an issue to get that fixed and then remove the context from the struct

2021-12-17 04:08 UTC, mimir-d approved these changes

2021-12-17 12:58 UTC, rihter007 commented on pkg/runner/base_test_suite_test.go
> +	Ctx    xcontext.Context
Opened a new issue: https://github.com/linuxboot/contest/issues/59

2021-12-17 12:58 UTC, merged

2021-12-19 00:57 UTC, rihter007 commented
Wtf, I have a strong feeling that I removed ctx from BaseSuite...
Will make a new PR