Move emission of EventTargetIn/EventTargetOut/EventTargetErr to StepRunner
linuxboot/contest pull request #65
Opened 2021-12-19 19:02 UTC by rihter007

Check for ErrTestStepReturnedUnexpectedResult in StepRunner

2021-12-19 19:03 UTC, rihter007 commented
It is not the last refactor iteration.

2022-02-05 20:28 UTC, mimir-d commented on pkg/runner/test_runner.go
> +		return nil
nit; this doesnt really do anything here anymore, but it's fine to keep for the "return" lower down

2022-02-05 22:20 UTC, mimir-d requested changes

2022-02-05 22:20 UTC, mimir-d commented on pkg/runner/step_runner.go
> +		sr.ioLoop(ctx, stepIn, stepOut, ev, bundle.TestStepLabel, resumeStateTargets)
this is unnecessarily complicated to me, once i read the logic in ioLoop. what's happening here is targets get inputed from _sr.input_, then go into _sr.ioLoop stepIn_ here, which is read by _sr.runningLoop stepIn_ chan, processed by the step plugin and pushed to _sr.ioLoop stepOut_ which outputs them to the caller.

instead of all that, i would suggest a simplification and formalization of the pipeline based on the actual flow: have 3 goroutines, one for ingestion (extract from ioLoop) - this passes to an intermediate channel (which should **not** be named _stepIn_), one for processing (the actual step plugin, reading from intermed chan) and out for output (extracted from ioLoop)

2022-02-13 22:06 UTC, rihter007 commented on pkg/runner/step_runner.go
> +		sr.ioLoop(ctx, stepIn, stepOut, ev, bundle.TestStepLabel, resumeStateTargets)
Yes, this is a bit convoluted.
So, the actual Step.Run() gets stepIn and stepOut (the standard names for input/output channel), so I would keep their names.

There is an Add() method that should add new targets to step.

The problem with making a single stepIn channel was that one should be able to close it (that notifies the underlying step that there will be no more targets and it can quit). So, to avoid panics, one should either take a lock on writing to channel (which is a possible dead-lock) or to introduce that intermediate channel that I called "input" (I'm ok to rename this one). And that caused all complexity.

I think that having 3 goroutines will not make things better, because the input+stepIn should be in one. But I agree that separating input and output will make the code clear.

2022-02-13 22:10 UTC, rihter007 commented on pkg/runner/step_runner.go
> +	targetsInfo := make(map[string]int)
Yes, the name is bad.
It should be called processingTargets, it reflects the targets that were sent into Step.

2022-02-13 22:13 UTC, rihter007 commented on pkg/runner/step_runner.go
> +				curInputTarget = inputTargets[len(inputTargets)-1]
It is because golang miss STL :(
Ideally this should be a dequeue, but I made a custom stack implementation

2022-02-13 22:15 UTC, rihter007 commented on pkg/runner/step_runner.go
> +		sr.ioLoop(ctx, stepIn, stepOut, ev, bundle.TestStepLabel, resumeStateTargets)
Note, the problem with stop gets fixed in PR70

2022-02-13 22:37 UTC, rihter007 commented on pkg/runner/step_runner.go
> +		sr.ioLoop(ctx, stepIn, stepOut, ev, bundle.TestStepLabel, resumeStateTargets)
Oh, I remembered a more important reason: we need to populate targetsInfo variable (bad name, agree) that contains information of all currently processed targets in Step.
We need to do that atomically with sending target to the stepIn channel (so we either need a lock or make them in a single goroutine).
Having a lock is bad, as Step plugin may process all targets in a single goroutine and may get a deadlock on sending results to the output channel. (which Step runner will not read, as it will be waiting on a lock)
(I understand that this explanation is convoluted, so I'm ready to talk it through).

2022-02-22 01:15 UTC, rihter007 commented on pkg/runner/step_runner.go
> +		sr.ioLoop(ctx, stepIn, stepOut, ev, bundle.TestStepLabel, resumeStateTargets)
I decided to rework it a little bit. The new code less effectively detects a very specific possible error in Step plugin implementation (like the current code), but in result it is a lot more simple.

2022-02-22 01:16 UTC, rihter007 commented on pkg/runner/step_runner.go
> +			targetsInfo[curInputTarget.ID]++
The number of currently processed targets. It could be 1 or 0 if everything is ok or -X if not.
It also tolerates duplicates (which are filtered by TargetsManager), I guess we should not put this check here as well

2022-02-22 01:17 UTC, rihter007 commented on pkg/runner/step_runner.go
> +		case stepInTmp <- curInputTarget:
The code is gone

2022-02-22 01:20 UTC, rihter007 commented on pkg/runner/test_runner.go
> +				resumeStateTargets = append(resumeStateTargets, *tgt.tgt)
Will add a comment.
In the current implementation ResumeState of a test is filled by a TestRunner. StepRunner gets only a chunk of generated by the step it talks to. We can rewrite it, but it is better to do in a separate PR

2022-02-22 01:26 UTC, rihter007 commented on pkg/runner/step_runner.go
> +		case stepInTmp <- curInputTarget:
the code should go

2022-02-22 01:31 UTC, rihter007 commented on pkg/runner/test_runner.go
> +		state := tgs
This is done because "golang" reuses the same loop variable and goroutine captures variables "by-reference"

2022-03-22 21:20 UTC, mimir-d commented on pkg/runner/test_runner.go
> +		state := tgs
ah ok, wasnt obvious at first sight; i would expect the same var name like `tgs := tgs`, to point out that a copy is being made for deref; that being said, the following style is preferred

```
go func(state *targetState){...}(tgs)
```

2022-03-22 22:12 UTC, mimir-d submitted a review, later dismissed
left a style comment on the var aliasing for goroutine

2022-03-22 22:14 UTC, mimir-d commented on pkg/runner/step_runner.go
> +				curInputTarget = inputTargets[len(inputTargets)-1]
even if so, generally speaking, you should separate the stack/dequeue impl from the consumer code rather than intertwine them

2022-03-23 12:01 UTC, mimir-d approved these changes

2022-03-23 12:07 UTC, merged