Retry test if targets acquiring failed
linuxboot/contest pull request #78
Opened 2022-02-23 20:19 UTC by rihter007

2022-02-25 01:58 UTC, mimir-d requested changes
would also be nice to have an explanation as to why the retry wasnt being done, and how you fixed it (#77 only covers _what_ happens). I understand how that works now, but it was after reading additional code that's not present in the PR.

2022-02-25 01:58 UTC, mimir-d commented on pkg/runner/job_runner.go
> +	acquireCtx, acquireCancel := xcontext.WithDeadline(ctx, time.Now().Add(j.TargetManagerAcquireTimeout))
there's a WithTimeout, to avoid the unecessary time.add operation

2022-02-25 01:58 UTC, mimir-d commented on pkg/runner/job_runner.go
> +			if err = testEventEmitter.Emit(ctx, eventData); err != nil {
nit, this "err" should be redefined for this context here, since you dont want the value outside the block

2022-02-25 01:58 UTC, mimir-d commented on pkg/target/target.go
> +func MarshalledErrPayload(err string) (json.RawMessage, error) {
nit, please make this look like the name of a function; it's missing the verb, so probably "MarshalErrPayload"

2022-02-25 01:58 UTC, mimir-d commented on pkg/target/target.go
> +	if err := json.Unmarshal(jsonPayload, &errorPayload); err != nil {
im not convinced this unmarshal is correct; the type of the output object should be a ptr, so that the unmarshaller can decode null input; so it should actually be "var payload *ErrPayload". please check

2022-02-25 01:58 UTC, mimir-d commented on pkg/target/target.go
> +	jsonPayload, err := payload.MarshalJSON()
im missing something; what's the point of this call?

2022-02-25 01:58 UTC, mimir-d commented on pkg/runner/job_runner.go
> +func (jr *JobRunner) acquireTargets(
nit, this should have a doc specifying why the error it's returning is retryable; it might as well not be, if other final errors are thrown (in the future), cancelation can be one

2022-02-25 01:58 UTC, mimir-d commented on pkg/runner/job_runner_test.go
> +	tm := stateFullTargetManager{
nit, seems to me like this could be a mock object; it would also cover a lot of other scenarios, like unexpected function calls, required calls, etc

2022-02-25 01:58 UTC, mimir-d commented on pkg/runner/job_runner_test.go
> +	require.Nil(s.T(), resumeState)
nit, you should just use "s.Nil"; same for the other requires

2022-02-26 16:28 UTC, rihter007 commented on pkg/runner/job_runner.go
> +			if err = testEventEmitter.Emit(ctx, eventData); err != nil {
goland showed me a warning... so I decided to do as it says

2022-02-26 22:46 UTC, rihter007 commented on pkg/runner/job_runner_test.go
> +	tm := stateFullTargetManager{
golang has a very raw Mocks concept, the result code looks almost same (even more LOCs a bit)

2022-02-26 22:47 UTC, rihter007 commented on pkg/runner/job_runner_test.go
> +	require.Nil(s.T(), resumeState)
I know :) I just want to be persistent everywhere and use require/assert TestFunc.

2022-02-26 22:52 UTC, rihter007 commented on pkg/target/target.go
> +	jsonPayload, err := payload.MarshalJSON()
Good question, I copied this code, so I decided to keep it unchanged, in general it does very little:

// MarshalJSON returns m as the JSON encoding of m.
func (m RawMessage) MarshalJSON() ([]byte, error) {
	if m == nil {
		return []byte("null"), nil
	}
	return m, nil
}

Let me rewrite it to become more clear

2022-02-27 19:16 UTC, mimir-d commented on pkg/target/target.go
> +	if err := json.Unmarshal(jsonPayload, &errorPayload); err != nil {
> you probably missed '&'

I didnt.  
I wrote an example [here](https://go.dev/play/p/bBlnYVWXJzY) to show the difference between ptr and value type in json unmashal. Since here you aren't using a ptr, a null json input will result in a default constructed ErrPayload, which you then return a pointer to (and could signal to an upstream consumer that there _was_ an error, and the payload happens to be identical to default ctor'd).
If this is intended, then ok. But I get the feeling that you want to return a nil, when the json input is null. In which case, the code should be:

```
var errPayload *ErrPayload
_ = json.Unmarshal(jsonPayload, &errorPayload)
return errPayload
```

2022-02-27 19:20 UTC, mimir-d approved these changes

2022-02-27 23:38 UTC, rihter007 commented on pkg/target/target.go
> +	if err := json.Unmarshal(jsonPayload, &errorPayload); err != nil {
Oh, thanks, I didn't know that

```
var errPayload *ErrPayload
_ = json.Unmarshal(jsonPayload, &errorPayload)
return errPayload
```
works

2022-02-27 23:40 UTC, merged

2022-02-28 16:15 UTC, rihter007 commented on pkg/target/target.go
> +	if err := json.Unmarshal(jsonPayload, &errorPayload); err != nil {
Ok, let me adopt the initial one to keep the identical behaviour

2022-02-28 16:27 UTC, mimir-d commented on pkg/target/target.go
> +	if err := json.Unmarshal(jsonPayload, &errorPayload); err != nil {
addressed in #79