TestStep variables proof of concept
linuxboot/contest pull request #83
Opened 2022-06-21 12:48 UTC by rihter007

PoC for https://github.com/linuxboot/contest/issues/25

Introduced a new interface for step plugins:
```
type StepsVariables interface {
	Add(tgtID string, name string, v interface{}) error
	Get(tgtID string, name string, v interface{}) error
}
```

that can add/read variables from current/previous steps.

A mapping between external->internal variables is represented as `StepVariablesMapping` type which was added to step bundles.

In order to keep PR short, will add parameters template + better testing including e2e in the next PR

2022-06-21 13:01 UTC, xaionaro commented
> Get(tgtID string, name string, v interface{}) error

It puts the value into `v`?

2022-06-21 13:10 UTC, rihter007 commented
> > `Get(tgtID string, name string, v interface{}) error`
> 
> It puts the value into `v`?

yes, probably I should rename method/variable for more clearity. v -> out

2022-06-22 11:06 UTC, rihter007 commented on pkg/pluginregistry/bundles.go
> +	return (ch >= 'a' && ch <= 'z') || (ch >= 'A' || ch <= 'Z')
bug: 

ch >= 'A' && ch <= 'Z'

fixed in the next PR

2022-06-24 10:38 UTC, xaionaro commented
> > > `Get(tgtID string, name string, v interface{}) error`
> > 
> > 
> > It puts the value into `v`?
> 
> yes, probably I should rename method/variable for more clearity. v -> out

Let's at least rename the variable `v` in the interface to `in` and `out` accordingly?

2022-06-24 10:44 UTC, xaionaro commented on pkg/pluginregistry/bundles.go
> +}
**nitpicking**

```
func isAlpha(c rune) bool {
    return unicode.IsLetter(c) || unicode.IsDigit(c)
}
```

2022-06-24 10:45 UTC, xaionaro commented on pkg/pluginregistry/bundles.go
> +		if ch >= '0' || ch <= '9' {
**nitpicking**
```
if unicode.IsDigit(ch)
```

2022-06-24 11:38 UTC, xaionaro commented on pkg/runner/test_runner.go
> +var _ test.StepsVariables = (*stepVariablesAccessor)(nil)
**nitpicking**

Can we put this to a dedicated file?

2022-06-24 12:17 UTC, xaionaro commented on pkg/runner/test_runner.go
> +func (sva *stepVariablesAccessor) Get(tgtID string, name string, out interface{}) error {
**warning**

What I do not like here that names `Add` and `Get` with the same variable name `name` imply like these are kinda symmetrical functions. So from the signature I would expect that this would work:
```
assertNoError(sva.Add("1", "someName", "someValue"))
var str string
assertNoError(sva.Get("1", "someName", &str))
```
but in reality they are not:
* `Add` puts a value where the name is not mapped.
* `Get` maps the name first.

I think either we need to rename one of `name` variables or one of functions... May be the next variant?
```
func (sva *stepVariablesAccessor) Get(tgtID string, handle string, out interface{}) error {
```
Or even
```
type VariableHandle string
func (sva *stepVariablesAccessor) Get(tgtID string, handle VariableHandle, out interface{}) error {
```
to compile-time check if somebody confused those two?

2022-06-24 14:29 UTC, xaionaro submitted a review, later dismissed
I have questions, request, but they can go in another PR. But the review wasn't careful, and I assume @mimir-d also wanted to go through, so I would recommend to wait :)

2022-06-24 14:29 UTC, xaionaro commented on pkg/runner/test_runner.go
> +	}
**question**

There are two cases because sometimes we start from scratch and sometimes we resume a job, or there is another reason of this?

2022-06-24 14:29 UTC, xaionaro commented on pkg/runner/test_runner.go
> +		return nil, fmt.Errorf("step '%s' didn't emit variable '%s' yet", stepLabel, name)
**nitpicking**

Let's add `tgtID` to the error message to be explicit that `didn't emit` for a specific target (but we did not mean that it did not emit such variable for any at all).

2022-06-24 14:29 UTC, xaionaro commented on pkg/runner/test_runner.go
> +	}
**nitpicking**

Again, this is because of pause/resumption? If so, can we leave a comment?

2022-06-24 14:52 UTC, xaionaro commented
My main concern here is that the PR contributes into tech debt we have in TestRunner. Let me quote myself from another chat:
> Basically it is a mess of different ideas intertwined in muddy implicit fuss.

2022-06-25 21:14 UTC, rihter007 commented on pkg/runner/test_runner.go
> +		}
I added a TODO in comments. The diff is huge already

2022-06-26 21:49 UTC, rihter007 commented
> My main concern here is that the PR contributes into tech debt we have in TestRunner. Let me quote myself from another chat:
> 
> > Basically it is a mess of different ideas intertwined in muddy implicit fuss.
> 
> But I guess solving this issue is a whole another epic story.

I would say the main tech debt is in convoluted state machine implementation. If it will be moved into a separate logic, everything will be straightforward. Saving additional info at the end of the TestRunner.Run is straightforward

2022-06-26 21:50 UTC, rihter007 commented on pkg/runner/test_runner.go
> +	}
yes

2022-06-26 21:54 UTC, rihter007 commented on pkg/runner/test_runner.go
> +		tgs.StepsVariables, err = tr.stepsVariables.getTargetStepsVariables(tgt.ID)
This code executes after all steps have been stopped, either due to pause or not.
At this stage all step variables will not change, so I just store the result in the state of corresponding target

2022-06-26 21:56 UTC, rihter007 commented on pkg/runner/test_runner.go
> +		tgs.StepsVariables, err = tr.stepsVariables.getTargetStepsVariables(tgt.ID)
We can always access StepsVariables of each target, but I think it will make code even more convoluted.

2022-06-26 21:56 UTC, rihter007 commented on pkg/runner/test_runner.go
> +func (sva *stepVariablesAccessor) Get(tgtID string, name string, out interface{}) error {
Good catch!

2022-06-27 10:01 UTC, rihter007 commented on pkg/runner/test_runner.go
> +	}
No, that is in case variables mapping wasn't specified in step description.
I added a separate error for this case for more clarity

2022-06-27 15:50 UTC, mimir-d requested changes
returning for the `v2` breakage and comments

2022-06-27 15:50 UTC, mimir-d commented on pkg/pluginregistry/bundles.go
> +	if testStepDescriptor.VariablesMapping != nil {
why do we need this variable mapping? in the e2e test in #85, you have
```
          parameters:
            args: ["{{ StringVar \"output_var\" }}"]
          variablesmapping:
            output_var: variablesstep.message
```
can it be just?
```
          parameters:
            args: ["{{ var `variablesstep.message` }}"]
```

2022-06-27 15:50 UTC, mimir-d commented on pkg/runner/test_runner.go
> +type stepVariables map[string]json.RawMessage
id try to find a different name for this, `variables` implies that theyre mutable. Something more like `stepOutputs`

2022-06-27 15:53 UTC, mimir-d commented
would also be useful to have a "permitted outputs" type of array in the plugin itself, and the framework checks if that's valid when emitting; like the Events one. this would also be able to be extracted as docs, otherwise there's no way of knowing what output a plugin produces without reading the code

2022-06-27 16:04 UTC, rihter007 commented on pkg/runner/test_runner.go
> +	StepsVariables map[string]stepVariables `json:"V,omitempty"` // maps steps onto emitted variables of each
I would certainly avoid using events for persistence, but for logging purposes it looks fine

2022-06-27 16:07 UTC, rihter007 commented on pkg/pluginregistry/bundles.go
> +	if testStepDescriptor.VariablesMapping != nil {
This is something we discussed in a meeting: there are two ways of accessing variables:
1. In parameters
2. Pure using variables interface (where the name of input variable is hardcoded)

In either case variables mapping is useful for early checking of correctness

2022-06-27 16:07 UTC, rihter007 commented on pkg/test/step.go
> +		if unicode.IsLetter(ch) || unicode.IsDigit(ch) || ch == '_' {
I personally find regex harder to read. But I don't have a strong opinion

2022-06-27 16:15 UTC, xaionaro commented on pkg/runner/test_runner.go
> +	StepsVariables map[string]stepVariables `json:"V,omitempty"` // maps steps onto emitted variables of each
> which means that everything gets lost

You mean in case of a crash of the application?

2022-06-27 16:19 UTC, rihter007 commented
> would also be useful to have a "permitted outputs" type of array in the plugin itself, and the framework checks if that's valid when emitting; like the Events one. this would also be able to be extracted as docs, otherwise there's no way of knowing what output a plugin produces without reading the code

I don't know, on the other hand it makes you each time to specify all the variables when using the plugin. We can add this later as improvement

2022-06-27 16:22 UTC, rihter007 commented on pkg/test/step.go
> +	Get(tgtID string, mappedName string, out interface{}) error
You can get different types of structures from the same serialised data.

2022-06-27 16:22 UTC, rihter007 commented on pkg/storage/limits/limits_test.go
> +		TestName: "AAA",
Sure, I guess I changed it when debugging and forgot to revert

2022-06-27 16:23 UTC, rihter007 commented on pkg/storage/limits/limits.go
> +func (v *Validator) validate(data string, dataName string, allowEmpty bool, maxDataLen int) error {
Forgot to remove

2022-06-27 16:24 UTC, rihter007 commented on pkg/storage/limits/limits.go
> +func (v *Validator) ValidateTestStepLabel(testStepName string) error {
Forgot to revert, thanks!

2022-06-27 16:25 UTC, rihter007 commented on pkg/runner/step_runner.go
> +		return bundle.TestStep.Run(ctx, inChannels, ev, stepsVariables, bundle.Parameters, resumeState)
It is not a complicated change, when we added resume state. We didn't make that.

2022-06-28 21:14 UTC, mimir-d commented on pkg/runner/test_runner.go
> +	StepsVariables map[string]stepVariables `json:"V,omitempty"` // maps steps onto emitted variables of each
yeah, but on a more general note, im hinting at making the server as stateless as possible

2022-06-28 21:15 UTC, mimir-d commented on pkg/test/step.go
> +		if unicode.IsLetter(ch) || unicode.IsDigit(ch) || ch == '_' {
the regex for this case is simple, hence my asking; `[a-zA-Z0-9_]+`

2022-06-28 21:17 UTC, mimir-d commented on pkg/test/step.go
> +	Get(tgtID string, mappedName string, out interface{}) error
im not following your answer

2022-06-28 21:24 UTC, mimir-d commented
> makes you each time to specify all the variables when using the plugin
yes, but it can also act as a filter; if youre only interested in some outputs, you only write those for that specific plugin. The main point is to make things obvious for the reader, and adds some safety on top.
eg.
```yaml
- name: cmd
  label: cmd0
  parameters:
    - ...
  outputs:
    - stdout

- name: echo
  label: echo0
  parameters:
    - message: "cmd said {{step_output `cmd0.stdout`}}"

# this would be an error
- name: echo
  label: echo1
  parameters:
    - message: "cmd said {{step_output `cmd0.stderr`}}"
```

> And to get a list of that permitted outputs one still needs to read either a doc or code
only valid for the first writer, these descriptors are usually a write once, read many kind of thing so it would have value for the readers

2022-06-29 10:26 UTC, rihter007 commented
> only valid for the first writer, these descriptors are usually a write once, read many kind of thing so it would have value for the readers
If you mean copy-paste of test descriptors :)

Anyway we can add it later if we start to feel the need of that kind of documentation

2022-06-29 10:30 UTC, rihter007 commented on pkg/runner/test_runner.go
> +	StepsVariables map[string]stepVariables `json:"V,omitempty"` // maps steps onto emitted variables of each
> yeah, but on a more general note, im hinting at making the server as stateless as possible

In that case it doesn't help. If a crash happens, the state will be lost no matter what. Who knows what did the step plugin do?

2022-06-29 10:31 UTC, rihter007 commented on pkg/runner/test_runner.go
> +type stepVariables map[string]json.RawMessage
But they are mutable

2022-06-29 10:32 UTC, rihter007 commented on pkg/pluginregistry/bundles.go
> +	if testStepDescriptor.VariablesMapping != nil {
Agreed that this feature is not required now. So, will remove to have a smaller change

2022-06-29 10:33 UTC, rihter007 commented on pkg/test/step.go
> +		if unicode.IsLetter(ch) || unicode.IsDigit(ch) || ch == '_' {
+ first digit is alpha only

2022-06-29 10:33 UTC, rihter007 commented on pkg/test/step.go
> +		if unicode.IsLetter(ch) || unicode.IsDigit(ch) || ch == '_' {
Also need "first digit is alpha only". That can be a simple if + your regex, but why not to do everything in a loop in that case?

2022-06-29 10:35 UTC, rihter007 commented on pkg/test/step.go
> +	Get(tgtID string, mappedName string, out interface{}) error
It is the same thing like with json.Unmarshal()

The {"SomeField": 10} could be deserialised into:
- map["SomeField"] = int(10) or uint(10)
- type MyStruct struct { SomeField int }
- ...

2022-06-29 11:20 UTC, rihter007 commented on pkg/runner/test_runner.go
> +	StepsVariables map[string]stepVariables `json:"V,omitempty"` // maps steps onto emitted variables of each
@mimir-d I will add emission of events in the next PR.

2022-06-29 20:33 UTC, mimir-d commented on pkg/runner/test_steps_variables.go
> +func (sva *stepVariablesAccessor) Get(tgtID string, stepLabel, name string, out interface{}) error {
id add some docs with examples for all of these public methods; if you wanna keep this signature instead of the one i proposed (which is similar to context.Value), it would be specified in the examples that users should not forget to "&out" here

2022-06-29 20:33 UTC, mimir-d commented on pkg/runner/test_steps_variables.go
> +func (tsv *testStepsVariables) checkInput(tgtID string, stepLabel string, name string) error {
mind if we use full nouns for parameters? "tgt" is a bit too terse, and the rest of the params are complete as well (eg. it's not stepLbl)

2022-06-29 20:33 UTC, mimir-d commented on pkg/test/step.go
> +		if unicode.IsLetter(ch) || unicode.IsDigit(ch) || ch == '_' {
`[a-zA-Z]\w*` is one line vs a for loop with special case for 0 + if len == 0

2022-06-29 20:36 UTC, mimir-d commented on pkg/test/step.go
> +	Get(tgtID string, mappedName string, out interface{}) error
well ok, but this is a consequence of using json raw message in the impl. if you look at https://pkg.go.dev/context#WithValue it can deal with returning `any` just fine and it's very similar to this code. anyway, i left a message for docs if you wanna keep this signature, so i'll resolve this one

2022-07-01 14:13 UTC, rihter007 commented on pkg/runner/test_runner.go
> +type stepVariables map[string]json.RawMessage
Same step plugin can change the values of the variable for the same target as **we agreed** during same "run course". But we can rename them as stepOutputs, as they become read-only after step finishes processing target
Initially I proposed that steps will generate variables in "return" that makes them solid read-only, but a little bit less handy.

2022-07-01 14:15 UTC, rihter007 commented on pkg/runner/test_steps_variables.go
> +func (sva *stepVariablesAccessor) Get(tgtID string, stepLabel, name string, out interface{}) error {
It is hard to forget &out here due to compile error, but I can add unit tests.
User should not normally use this method, as it will be handled in parameter.Expand (implemented in the next diff)

2022-07-01 20:41 UTC, rihter007 commented on pkg/runner/step_runner.go
> +		return bundle.TestStep.Run(ctx, inChannels, ev, stepsVariables, bundle.Parameters, resumeState)
I'm ok to do a version change, np :)

2022-07-01 20:55 UTC, rihter007 commented on pkg/runner/step_runner.go
> +		return bundle.TestStep.Run(ctx, inChannels, ev, stepsVariables, bundle.Parameters, resumeState)
Wait, there are just to options:
- add /v2 to the module path that will be followed adding /v2 in all imports here
- add a release tag say v2.0.1 in that case all clients will be importing the old version by default.
I personally prefer the latter (fiano does so)

2022-07-01 20:58 UTC, rihter007 commented on pkg/pluginregistry/bundles.go
> +	if err := test.CheckVariableName(label); err != nil {
Because they are having the same constraints.

2022-07-06 22:57 UTC, mimir-d commented on pkg/pluginregistry/bundles.go
> +	if err := test.CheckVariableName(label); err != nil {
then you should rename the func to encompass both usages

2022-07-06 22:59 UTC, mimir-d commented on pkg/runner/test_steps_variables.go
> +func (sva *stepVariablesAccessor) Get(tgtID string, stepLabel, name string, out interface{}) error {
you get a compile error if you dont ref a variable here? why? both satisfy interface{} (btw, you might wanna use `any`)

2022-07-06 23:01 UTC, mimir-d commented on pkg/pluginregistry/bundles.go
> +	if err := test.CheckVariableName(label); err != nil {
the error type is also weird; the user is gonna see "invalid variable format" for the label. and wont have any idea why that's invalid and why it should be a "variable"

2022-07-06 23:08 UTC, mimir-d commented on pkg/runner/step_runner.go
> +		return bundle.TestStep.Run(ctx, inChannels, ev, stepsVariables, bundle.Parameters, resumeState)
ok for the git tag; but you need to start a release before merging this. currently version is based on hash because there are no releases and therefore it's identical to the main branch. later, even on v2 tag, we'd still be importing the main branch hash because v2 is frozen, and then if there's no v1 release, everyone else can either import latest hash or v2, both of which are breaking their api

2022-07-06 23:12 UTC, mimir-d commented on pkg/runner/test_runner.go
> +type stepVariables map[string]json.RawMessage
> Same step plugin can change the values of the variable for the same target

might be something i missed but what does this mean? once a step is finished with a target, in the same run id, how would it change anything? it never executes again for that target+run_id

even if it did change something, as far as the consumer is concerned, theyre readonly/const. and naming them variables implies that the consumer can mutate them, which isnt wanted

2022-07-06 23:14 UTC, mimir-d commented on pkg/runner/test_runner.go
> +type stepVariables map[string]json.RawMessage
arguably the point with consumer view is mostly for the test descriptor, there was the variables naming there. but if that were to be outputs, might as well be consistent and name them outputs in the code as well

2022-07-06 23:16 UTC, mimir-d commented on pkg/runner/test_steps_variables.go
> +func (sva *stepVariablesAccessor) Get(tgtID string, stepLabel, name string, out interface{}) error {
> User should not normally use this method

yes, but the code writers are also users. and having some docs, even minimal, for public methods, even if internally public, is a good thing

2022-07-06 23:21 UTC, mimir-d commented on pkg/test/step.go
> +		if unicode.IsLetter(ch) || unicode.IsDigit(ch) || ch == '_' {
im gonna call in an arbiter. @xaionaro , you get the deciding vote

2022-07-08 22:07 UTC, rihter007 commented on pkg/test/step.go
> +		if unicode.IsLetter(ch) || unicode.IsDigit(ch) || ch == '_' {
@mimir-d Is it really worth discussing?
Just place your code, I will copy paste it in PR

2022-07-08 22:09 UTC, rihter007 commented on pkg/runner/test_runner.go
> +type stepVariables map[string]json.RawMessage
I renamed it internally long ago, don't worry :) I was just waiting for other items to update PR. I just made a comment to clarify that during the same run, a test step is eligible to change the variable of the same target.

2022-07-08 22:10 UTC, rihter007 commented on pkg/pluginregistry/bundles.go
> +	if err := test.CheckVariableName(label); err != nil {
@mimir-d I'm ok to rename, please add your variant.

2022-07-08 22:11 UTC, rihter007 commented on pkg/runner/test_steps_variables.go
> +func (sva *stepVariablesAccessor) Get(tgtID string, stepLabel, name string, out interface{}) error {
I will add it in the comments

2022-07-08 22:12 UTC, rihter007 commented on pkg/runner/step_runner.go
> +		return bundle.TestStep.Run(ctx, inChannels, ev, stepsVariables, bundle.Parameters, resumeState)
Will add v1 tag

2022-07-12 08:29 UTC, mimir-d commented on pkg/pluginregistry/bundles.go
> +	if err := test.CheckVariableName(label); err != nil {
`CheckIdentifier`

2022-07-20 15:37 UTC, rihter007 commented on pkg/runner/test_steps_variables.go
> +func (sva *stepVariablesAccessor) Get(tgtID string, stepLabel, name string, out interface{}) error {
Should be done

2022-07-25 21:21 UTC, mimir-d approved these changes

2022-07-25 21:21 UTC, mimir-d commented on pkg/test/step.go
> +	if len(s) == 0 {
no longer needed, checked by regex

2022-08-07 15:35 UTC, rihter007 commented on pkg/test/step.go
> +	if len(s) == 0 {
Unfortunately it can't be omitted as FindString is used with further length comparison.
(MatchString doesn't finds any match and doesn't suit our needs)

2022-08-07 15:38 UTC, rihter007 commented
Rebased the PR. @mimir-d could you please restamp it?

2022-08-07 19:31 UTC, rihter007 commented
Found a bug introduced by my previous PR, the fix is in https://github.com/linuxboot/contest/pull/121

2022-08-08 12:52 UTC, mimir-d approved these changes

2022-08-08 12:53 UTC, merged