Add versioning to json test descriptor
linuxboot/contest pull request #89
Opened 2022-06-27 15:54 UTC by mahmednabil109

In this merge request, I added the version field to the job descriptor , so that the server can check that it runs jobs that can understand. The check is done before the start of the job by calling `CheckVersion` on the job descriptor. This resolves #20.

2022-06-27 16:09 UTC, mimir-d requested changes
this is great, very clean code.

im returning for the TestIncompatibleVersions because it has a logic bug

2022-06-27 16:09 UTC, mimir-d commented on pkg/job/job.go
> +const CurrentDescriptorVersion string = "1.0"
nit; this would make it easier to use in the code and avoids the (non-failing) conversions

```suggestion
const JobDescriptorMajorVersion uint = 1
const JobDescriptorMinorVersion uint = 0
```

2022-06-27 16:09 UTC, mimir-d commented on pkg/job/job.go
> +			"Version Error: The Job Descriptor Version %s is't compatible with the Server's %s",
nit
```suggestion
			"Version Error: The Job Descriptor version '%s' is not compatible with the server: '%s'",
```

2022-06-27 16:09 UTC, mimir-d commented on pkg/job/job_test.go
> +func TestInCompitableVersions(t *testing.T) {
```suggestion
func TestIncompatibleVersions(t *testing.T) {
```

2022-06-27 16:09 UTC, mimir-d commented on pkg/job/job_test.go
> +	validJd := Descriptor{
nit; in go, the guideline is to use all caps for acronyms; here it would be `validJD`, but since this is a very limited scope, you can just use `valid` or `desc` or `descriptor`

2022-06-27 16:09 UTC, mimir-d commented on pkg/job/job_test.go
> +			(&Descriptor{Version: c.version}).CheckVersion(),
i think you dont need the parens here (should check)
```
&Descriptor{...}.CheckVersion()
```

2022-06-27 16:09 UTC, mimir-d commented on pkg/job/job_test.go
> +func TestInValidVersion(t *testing.T) {
```suggestion
func TestInvalidVersion(t *testing.T) {
```

2022-06-27 16:09 UTC, mimir-d commented on pkg/job/job_test.go
> +	// CurrentVersion "1.0"
this wont always be the case, so when we update to version 2.1 later on, this test will fail. You should find a different way of writing this test to make sure it accounts for that

2022-06-27 16:12 UTC, rihter007 requested changes
Good code, just fix the nits and make tests green :)

2022-06-27 16:12 UTC, rihter007 commented on pkg/job/job_test.go
> +		Version: "1.0",
nit

I would use the constant, in order not to break the test when it changes

2022-06-27 16:12 UTC, rihter007 commented on pkg/job/job.go
> +	if d.Version == "" {
@rminnich are we ok with this breaking change?

2022-06-27 16:12 UTC, rihter007 commented on pkg/job/job.go
> +	if d.Version == "" {
@rminnich I guess we should modify client first in order not to break compatibility?

2022-06-27 16:17 UTC, mimir-d commented
as per discussion, we should also modify contestcli to add this field to the input json if it's missing (and should have the same value from the job package)

2022-06-27 21:20 UTC, mahmednabil109 commented on pkg/job/job_test.go
> +			(&Descriptor{Version: c.version}).CheckVersion(),
It won't work. I think the "." precedes the "&"

2022-06-27 21:48 UTC, mimir-d commented on pkg/job/job_test.go
> +func TestIncompitableVersions(t *testing.T) {
```suggestion
func TestIncompatibleVersions(t *testing.T) {
```

2022-06-27 21:57 UTC, mimir-d requested changes

2022-06-27 21:57 UTC, mimir-d commented on pkg/config/jobdescriptor.go
> +	if _, ok := jobDesc["Version"]; !ok {
this should be in contestcli code; it only makes sense for the client to add this info if it's missing from the user input, not for the parser code here (otherwise things other than clients will maybe use this code and incorrectly add that version number)

2022-06-27 22:02 UTC, mahmednabil109 commented on pkg/config/jobdescriptor.go
> +	if _, ok := jobDesc["Version"]; !ok {
I saw that this function is not called anywhere but in the CLI `run` function , so i assumed it's dedicated for it.
But, I will extract the addition of the version field

2022-06-27 22:07 UTC, mahmednabil109 commented on pkg/config/jobdescriptor.go
> +const JobDescriptorVersion string = "1.0"
The `const` declaration will not allow me. should i change it to `var` ?

2022-06-27 22:12 UTC, mahmednabil109 commented on pkg/config/jobdescriptor.go
> +	if _, ok := jobDesc["Version"]; !ok {
Also, the function converts from `JSON | YAML` back to `JSON`, so if i need to add fields I should add it before the last serialisetion or I will have to parse and serialize the JSON again !!

2022-06-27 22:19 UTC, mahmednabil109 commented on pkg/config/jobdescriptor.go
> +const JobDescriptorVersion string = "1.0"
Maybe yes, as it changes according to what the server supports.

2022-06-27 23:02 UTC, mimir-d commented on pkg/config/jobdescriptor.go
> +const JobDescriptorVersion string = "1.0"
this wont be an issue when you move the code to contestcli

2022-06-28 10:04 UTC, mimir-d approved these changes

2022-06-28 13:38 UTC, merged