Add simple status REST endpoint
linuxboot/contest pull request #99
Opened 2022-07-11 13:18 UTC by mahmednabil109

- added new server to collect the logging
- added a simple status endpoint

Signed-off-by: Mohamed Abokammer <mahmednabil109@gmail.com>

2022-07-11 20:02 UTC, rihter007 commented on cmds/logger/server/server.go
> +func Main(cmd string, args []string, sigs <-chan os.Signal) error {
all command line parsing should happen in func main(), as well as signal processing.

To Stop Main, one can use a Context object.

2022-07-12 09:14 UTC, mimir-d commented on cmds/logger/server/server.go
> +func intRouter() *gin.Engine {
is this `initRouter`?

2022-07-12 09:34 UTC, mimir-d commented on cmds/logger/server/server.go
> +}
> There should be a dedicated entity which performs user requests, abstracted from a specific network interface.

I dont understand this one. The server listens on all network interfaces. What is this dedicated entity that's supposed to abstract a network interface?

> HTTP REST API

This is explicitly desired to be http based.

> place for flag parsing and other CLI-related stuff. I usually do that in main

added more details for this in @rihter007 's comment

> Otherwise it is quite difficult to reuse the code in an internal infra

This will be used as a binary internally. It should be enough to import this `server` package. Also, we should not have discussions of internal infra on github.

> mixing responsibilities in the code usually leads to a lot of extra coupling in the code

where's the mixing of responsabilities? this is the most basic http server with a status rest endpoint.

> And more borders are drawn between different semantic layers of what is going on -- the better.... (and rest)

This discussion looks a lot like premature optimization to me. For what the code in this PR is supposed to do, little of that applies. I get the general intent and I agree that further on the design needs to be loosely coupled, abstracted, etc.

2022-07-12 09:36 UTC, mimir-d requested changes
returning for the rename of `Main` to `Serve`. Also, please rename this package as well, from `logger` to `admin_server` (or something to that account, im not particularly fond of `admin_server`). It will have more stuff in it than just this log inspection part.

2022-07-12 16:10 UTC, mimir-d commented on cmds/admin_server/main.go
> +	signal.Notify(sigs, syscall.SIGINT, syscall.SIGTERM, syscall.SIGUSR1)
just keep sigint here

2022-07-12 16:15 UTC, mimir-d commented on cmds/admin_server/server/server.go
> +			serverErr = err
makes more sense to do this the other way around

```
go func(){
   <-ctx.Done()
   server.Close()
}()

if err := server.ListenAndServe(); err != ... closed {
    return err
}

return ctx.Err()
```

2022-07-12 16:15 UTC, mimir-d commented on cmds/admin_server/server/server.go
> +	// on cancle close the server
```suggestion
	// on cancel close the server
```

2022-07-12 16:15 UTC, mimir-d commented on cmds/admin_server/server/server.go
> +	log.Errorf("Closeing the server")
```suggestion
	log.Debugf("Closing the server")
```

2022-07-12 16:16 UTC, mimir-d requested changes
left some required changes

2022-07-13 16:04 UTC, mimir-d commented on cmds/logger/server/server.go
> +}
> Well, it won't work for people who use gRPC or/and Thrift to route requests.

What requests specifically? This is a web frontend. The data from the REST endpoints is consumed by said frontend.

2022-07-13 16:04 UTC, mimir-d commented on cmds/logger/server/server.go
> +func Main(cmd string, args []string, sigs <-chan os.Signal) error {
yeah, latest commit is good

2022-07-13 16:05 UTC, mimir-d approved these changes

2022-07-13 16:07 UTC, mimir-d commented
dont merge yet; the commits history looks weird

2022-07-13 16:10 UTC, mimir-d commented
ok, i see what happened; in the fork repo, upstream was pulled in the middle of the feature branch; This leads to complicated histories, so please rebase your branch (in fork) on latest pull from upstream and remove the inner commit from the existing 3.

2022-07-13 16:10 UTC, mimir-d requested changes
waiting for the history fix

2022-07-13 16:39 UTC, mimir-d approved these changes

2022-07-13 16:46 UTC, merged